// All the rendered content lives here as raw markdown strings.
// We store the raw markdown as an array of lines joined with \n so we
// avoid tangling with backticks and dollar signs in JS template literals.

window.CONTENT = {};

/* ---------- README.md ---------- */
CONTENT.README = [
'<div class="readme-hero">',
'  <div class="super">',
'    <span>\u{1F4E6} jake-ruth</span>',
'    <span class="ver">v13.0.0</span>',
'    <span>·</span>',
'    <span>release: 2026-04</span>',
'  </div>',
'',
'  # Jake Ruth',
'',
'  <div class="tagline">',
'    Founder. Senior engineer. Occasional unicyclist on Rubik\'s cubes.<br/>',
'    Thirteen years shipping. One chapter ending, another beginning.',
'  </div>',
'</div>',
'',
'<div class="badge-row">',
'  <a class="shield" data-color="orange" href="#stock-unlock"><span class="k">YC</span><span class="v">W22</span></a>',
'  <a class="shield" data-color="blue" href="#overview"><span class="k">based</span><span class="v">NYC</span></a>',
'  <a class="shield" data-color="green" href="#hire-options"><span class="k">status</span><span class="v">available</span></a>',
'  <a class="shield" data-color="purple" href="#philosophy"><span class="k">AI</span><span class="v">driver-seat</span></a>',
'  <a class="shield" data-color="gray" href="#timeline"><span class="k">years shipping</span><span class="v">13</span></a>',
'  <a class="shield" data-color="yellow" href="#faq"><span class="k">license</span><span class="v">market rate + equity</span></a>',
'  <a class="shield" data-color="red" href="#contact"><span class="k">3x3 avg</span><span class="v">13.95s</span></a>',
'</div>',
'',
'<div class="avatar-row">',
'  <div class="avatar">JR</div>',
'  <div>',
'    <div class="handle">@JakeRuth <small>he/him · jake@stockunlock.com · NYC area</small></div>',
'  </div>',
'</div>',
'',
'> [!NOTE]',
'> Re-entering the workforce. Running Stock Unlock has been on autopilot for ~15 months. Open to full-time roles, contract work, or equity-founding conversations.',
'',
'## Overview',
'',
'I write software. I have for thirteen years, across three real companies and one that didn\'t work. I took AP Computer Science in the last year of high school because I refused to take AP Calculus; I fell in love with it in the first week. Everything downstream came from that sideways pivot.',
'',
'I was employee ~50ish at Oscar Health under Alan Warren, left at ~150+, skipped the manager track on purpose. I then co-founded Stock Unlock, led the YC W22 interview, raised $1.335M seed, scaled the team to eight and the customer base to thousands. The company operates profitably today with three people running day-to-day. I moved to key-decisions-only in late 2024.',
'',
'What I want next is a team I\'d pick, working on something I\'d want my name on, with AI treated as a first-class tool rather than a costume. That\'s it.',
'',
'## Quick Start',
'',
'Install Jake in three commands.',
'',
'```bash',
'# Hire Jake Ruth',
'$ email jake@stockunlock.com',
'$ # Responses typically within 1 business day, ET',
'',
'# Optional: view the source',
'$ open https://github.com/JakeRuth',
'```',
'',
'> [!TIP]',
'> No recruiter middleman required. Email direct. If the problem is interesting, you\'ll hear back fast.',
'',
'## What\'s in the box',
'',
'- **13 years shipping production code** across CommerceHub, Oscar Health, and Stock Unlock.',
'- **Founder experience that isn\'t theoretical.** Led a YC interview. Raised $1.335M. Hired eight people. Let them go gracefully when the business shape changed.',
'- **Full-stack range.** Python, TypeScript, Golang, Java, Groovy. React since pre-hooks. React Native since v0.13.',
'- **Infra fluency.** AWS (SES, EC2, S3, Route53), Docker Compose, Postgres, SRE-adjacent on-call.',
'- **AI-native, done right.** Claude Code, Codex, Cursor, Open Hands. Human-reviewed business logic and architecture. Driver in the driver\'s seat.',
'- **Edge cases covered.** Took down prod as an intern. Apologized before anyone spoke. Manager said the system was the problem.',
'- **Not just code.** Raised a seed. Carried culture. Interviewed engineers. Pushed back publicly on post-IPO benefit cuts. Wrote a Python script to win a co-founder.',
'',
'## Timeline',
'',
'A real markdown table, because a CV is a table pretending to be prose.',
'',
'| Year | Milestone | Why it mattered |',
'|---|---|---|',
'| 2010 | AP Computer Science, senior year of HS | Took it to dodge AP Calc. Fell in love in week one. |',
'| 2011–2015 | SUNY Albany, BS CS + Applied Math | 3.88 GPA, Dean\'s List every semester. |',
'| 2013 | ACM President | Took over a failing club. Recruited 20+. Tekkapalooza field trip → CommerceHub. |',
'| 2013–2016 | CommerceHub | Intern then FTE. Learned real engineering: code reviews, micro-services, test discipline. |',
'| 2015–2016 | Youni (co-founder, CTO) | Social app on React Native v0.13. Thousands of signups, couldn\'t solve cold-start. Shut down. |',
'| 2017–2021 | Oscar Health | ~50 engineers → ~150+. Associate → Mid → Senior. Declined manager track. |',
'| 2020–2021 | The Daniel Pronk emails | Wrote a Python script to automate his weekend work. Wouldn\'t stop emailing. |',
'| 2021-06 | Left Oscar to co-found Stock Unlock | Brought Nick Puljik. YC reached out cold on LinkedIn. |',
'| 2022-01 | Seed round: $1.335M | $500K YC SAFE + $835K other investors. I led the YC interview. |',
'| 2022-02 | YC W22 demo day | 400 paying users in two weeks. 800–900 at seed close. |',
'| 2022–2024 | Scaling Stock Unlock | Thousands of customers. Eight employees at peak. |',
'| 2024-12 | Stepped back to maintenance | Three FTEs run day-to-day. Key decisions only. Profit over growth. |',
'| 2025–2026 | AI-driven renaissance | Opus 4.5 was the tipping point. SU marketing, SEO/GEO, Customer.io → SES migration, internal Discord bot. |',
'| 2026-04 | Re-entering the workforce | Getting married. Redefining next chapter. |',
'',
'## Featured Projects',
'',
'<div class="project-grid">',
'  <div class="project-card" data-color="green">',
'    <div class="pc-head">',
'      <span class="pc-name">stock-unlock</span>',
'      <span class="pc-type">SaaS · YC W22</span>',
'    </div>',
'    <div class="pc-body">',
'      Software that doesn\'t rip off retail investors. Built, scaled to 8 people and thousands of paying customers. Profitable. Runs today with three FTEs. I\'m not full-time.',
'    </div>',
'    <div class="pc-meta">',
'      <span>★ ~$450K ARR</span><span>⑂ 8 peak</span><span>● profitable</span>',
'    </div>',
'  </div>',
'',
'  <div class="project-card" data-color="purple">',
'    <div class="pc-head">',
'      <span class="pc-name">oscar-chatbot</span>',
'      <span class="pc-type">internal tool</span>',
'    </div>',
'    <div class="pc-body">',
'      Built with Peter at Oscar Health from hackathon scraps. Started as a HipChat emoji pipeline. Became a command-routable bot the care-ops team actually used.',
'    </div>',
'    <div class="pc-meta"><span>● shipped</span><span>● internal-only</span></div>',
'  </div>',
'',
'  <div class="project-card" data-color="orange">',
'    <div class="pc-head">',
'      <span class="pc-name">customerio-to-ses</span>',
'      <span class="pc-type">cost optimization</span>',
'    </div>',
'    <div class="pc-body">',
'      Migrated Stock Unlock off Customer.io to self-hosted AWS SES with custom admin panels. Built largely with AI. Saved $5–6K/yr. One weekend of focused work.',
'    </div>',
'    <div class="pc-meta"><span>★ -$6K/yr</span><span>● AI-assisted</span><span>● prod</span></div>',
'  </div>',
'',
'  <div class="project-card" data-color="red">',
'    <div class="pc-head">',
'      <span class="pc-name">discord-ops-bot</span>',
'      <span class="pc-type">AI infrastructure</span>',
'    </div>',
'    <div class="pc-body">',
'      Tightly-permissioned Discord bot on EC2 via Docker Compose. Built with Open Hands. Non-technical teammates query logs, errors, code, and user data in natural language.',
'    </div>',
'    <div class="pc-meta"><span>● deployed</span><span>● docker-compose</span></div>',
'  </div>',
'',
'  <div class="project-card" data-color="gray">',
'    <div class="pc-head">',
'      <span class="pc-name">stockunlock-webflow</span>',
'      <span class="pc-type">marketing rebuild</span>',
'    </div>',
'    <div class="pc-body">',
'      Rewrote the SU marketing site in Webflow with AI-assisted code. 10x\'d the marketing footprint. Overhauled SEO and GEO.',
'    </div>',
'    <div class="pc-meta"><span>● AI-assisted</span><span>● 10x footprint</span></div>',
'  </div>',
'',
'  <div class="project-card" data-color="purple">',
'    <div class="pc-head">',
'      <span class="pc-name">grails-shiro-guard</span>',
'      <span class="pc-type">open source</span>',
'    </div>',
'    <div class="pc-body">',
'      Grails plugin for permission-string caching from the CommerceHub era. Still on GitHub if you\'re into Groovy.',
'    </div>',
'    <div class="pc-meta"><span>● open source</span></div>',
'  </div>',
'</div>',
'',
'## Stock Unlock',
'',
'> [!NOTE]',
'> **How to read this section.** Built it. Scaled to 8 employees and thousands of paying customers. Profitable side business today. Not full-time. Redefining next chapter.',
'',
'It started because Daniel Pronk spent five to ten hours every weekend on Excel sheets for his investing YouTube content. I wrote a Python automation in a weekend and emailed it to him for free. He ignored me for weeks. He replied eventually to make me stop. Instead of going away, I hopped on a video call, cracked a beer, and kept going.',
'',
'YC reached out cold via LinkedIn before we applied. Nick Puljik came over from Oscar. I led the YC interview. We closed $1.335M — $500K from YC, $835K from other investors. Peak eight employees, thousands of paying customers, roughly $450K ARR at its top.',
'',
'The core conviction was simple and still is: **overcharging for bad software is theft from people who can\'t afford to be robbed.** A competitor at the time computed a "margin of safety score" as `current_price / all_time_high`. I called that what it was. Stock Unlock exists partly as a response to it.',
'',
'In late 2024 the growth curve flattened and honest math told me the business was in a different shape. I moved to maintenance. Three FTEs run day-to-day now. The company is profitable. I\'m not the person running it every day anymore. I\'m redefining what\'s next.',
'',
'## Philosophy',
'',
'> Driver in the driver\'s seat, not driven by the car.',
'',
'That\'s the whole thing, most of the time. The distinction between vibe coding and software engineering is real. AI writes more code than I do now — and I read every line before it ships. Human-reviewed for business logic, security, and architecture. AI-only acceptable for static front-end visualization. Opus 4.5 was the inflection point for me; currently heavy on Claude Code + Codex + CMUX.',
'',
'```python',
'# The pattern, in one function',
'def ship(change):',
'    diff = ai.write(change.spec)',
'    review = human.review(',
'        diff,',
'        attention=["business_logic", "security", "architecture"]',
'    )',
'    if review.green():',
'        return change.ship()',
'    return ship(change.with_feedback(review))',
'```',
'',
'What this isn\'t: agentic roulette. What it is: tools applied deliberately.',
'',
'## Hire options',
'',
'> [!WARN]',
'> Pricing UI is shown for clarity. Real numbers live over email.',
'',
'| Tier | For | Terms | CTA |',
'|---|---|---|---|',
'| **Full-Time Employment** | The main thing. Senior IC, founding engineer, or early-stage CTO. NYC / remote / hybrid. | Market comp + equity | [Email Jake](mailto:jake@stockunlock.com?subject=Full-time) |',
'| **Equity Founding** | Zero-to-one conviction bets. Problem I\'d care about. | Co-founder track, real equity | [Let\'s talk](mailto:jake@stockunlock.com?subject=Founding) |',
'| **Contract Engagement** | Defined deliverable, defined timeline. | Contact | [Talk to Jake](mailto:jake@stockunlock.com?subject=Contract) |',
'| **Starter Conversation** | If you\'re not sure. | Free | [Email](mailto:jake@stockunlock.com?subject=Hello) |',
'',
'> [!TIP]',
'> Not looking to manage unless the team is right. Happy to carry culture either way.',
'',
'## FAQ',
'',
'<details>',
'  <summary><strong>Why are you leaving Stock Unlock?</strong></summary>',
'  <p>I\'m not leaving — I\'ve already stepped back. I moved to key-decisions-only in late 2024. Three full-time employees run the day-to-day. The company is profitable. This is what a won battle in maintenance mode looks like, not an exit announcement.</p>',
'</details>',
'',
'<details>',
'  <summary><strong>What\'s the unicycle cube thing?</strong></summary>',
'  <p>At an Oscar Health talent show I rode a unicycle while solving a Rubik\'s cube. Josh Kushner was in the audience. 3x3 competitive average: 13.95 seconds. I competed 2008–2014 at Northeast US and Nationals.</p>',
'</details>',
'',
'<details>',
'  <summary><strong>Would you manage a team?</strong></summary>',
'  <p>Yes, if the team is right. I declined the manager track at Oscar on purpose — not because I dislike people, but because I was closer to my own work than to theirs. I\'ve since hired eight, carried culture, and fired gracefully. I\'d do it again for the right team.</p>',
'</details>',
'',
'<details>',
'  <summary><strong>How do you actually use AI day-to-day?</strong></summary>',
'  <p>Claude Code and Codex for most real work, CMUX to wrap it, occasional Cursor. I treat the agent like a junior engineer with a memory problem: I write crisp specs, I review every diff that touches business logic or security, I\'m happy to let it run loose on static presentational code. Opus 4.5 was the point where I stopped arguing with myself about whether this was actually working.</p>',
'</details>',
'',
'<details>',
'  <summary><strong>Do you take recruiter emails?</strong></summary>',
'  <p>Email me directly. Recruiter emails get read, but replies are slower and shorter. If you\'re hiring and you can write the three sentences about what you\'re building and why, that\'s enough.</p>',
'</details>',
'',
'<details>',
'  <summary><strong>What won\'t you work on?</strong></summary>',
'  <p>"Fisher-Price" software that looks polished but breaks under real use. Bureaucracy and politics over shipping. Anything that\'s designed to overcharge people who can\'t afford to be robbed.</p>',
'</details>',
'',
'<details>',
'  <summary><strong>Where do you live?</strong></summary>',
'  <p>NYC area. Westchester NY as a kid, Albany for school, NYC for work and founding. Getting married in 2026.</p>',
'</details>',
'',
'## Contact',
'',
'<div class="contact-card">',
'  <div class="row"><span class="label">email</span><a href="mailto:jake@stockunlock.com">jake@stockunlock.com</a></div>',
'  <div class="row"><span class="label">github</span><a href="https://github.com/JakeRuth" target="_blank" rel="noopener">github.com/JakeRuth</a></div>',
'  <div class="row"><span class="label">resume</span><a href="../../official_resume.pdf" target="_blank" rel="noopener">official_resume.pdf</a></div>',
'  <div class="row"><span class="label">location</span>NYC area · open to remote / hybrid</div>',
'  <div class="row"><span class="label">response</span>Fast during ET business hours. Email &gt; DMs.</div>',
'  <div class="row"><span class="label">as of</span>2026-04-20</div>',
'</div>',
'',
'> Prefer email. If it lands in my inbox with three clear sentences, you\'ll hear back within a business day.',
'',
'---',
'',
'<p class="muted" style="text-align:center; font-size:12px;">',
'  README.md · rendered on file://localhost ·',
'  <a href="#top">back to top</a> ·',
'  <a href="#" id="hint-raw">view source</a>',
'</p>',
''
].join('\n');

/* ---------- PROJECTS.md ---------- */
CONTENT.PROJECTS = [
'# PROJECTS.md',
'',
'A longer-form list. For the short version, see [README.md](#).',
'',
'## Stock Unlock — YC W22',
'',
'Software that doesn\'t rip off retail investors. Co-founded with Daniel Pronk and Nick Puljik. Raised $1.335M seed in January 2022 ($500K YC SAFE + $835K other investors). Peak team of 8, thousands of paying customers, ~$450K ARR. Operates profitably today with three full-time employees. I moved to key-decisions-only in late 2024.',
'',
'> Stock Unlock exists partly as a response to a competitor whose "margin of safety score" was `current_price / all_time_high`. That\'s not analysis.',
'',
'## Oscar internal chatbot',
'',
'Built with my friend Peter from hackathon scraps. Started as a HipChat emoji pipeline and evolved into a command-routable bot that care-ops actually used. Over-engineered on purpose.',
'',
'## Customer.io → AWS SES migration',
'',
'Self-hosted on AWS SES with custom admin panels. Built largely with AI assistance. Saved $5–6K/yr. One person, one focused weekend.',
'',
'```ts',
'// Roughly the shape',
'const sender = new SESSender({ region: "us-east-1" });',
'const templates = loadTemplates("./templates");',
'const admin = buildAdminPanel({ sender, templates, auth: requireStockUnlockStaff });',
'```',
'',
'## Internal Discord bot',
'',
'Deployed via Docker Compose on EC2. Built with Open Hands. Tight permissioning so non-technical teammates can query logs, errors, code, and user data in natural language without being able to do anything they shouldn\'t.',
'',
'## Stock Unlock Webflow rewrite',
'',
'Rewrote the full marketing site in Webflow with AI-assisted code. 10x\'d marketing footprint. Overhauled SEO and GEO.',
'',
'## Youni (shut down)',
'',
'College-focused social iOS app on React Native v0.13. Thousands of signups across two campuses. Couldn\'t solve cold-start. Wound down within ~6 months. I co-founded it and ran CTO.',
'',
'## grails-shiro-guard',
'',
'A Grails plugin for permission-string caching, open-sourced during my CommerceHub era. Still on GitHub if you\'re into Groovy.',
''
].join('\n');

/* ---------- CONTACT.md ---------- */
CONTENT.CONTACT = [
'# CONTACT.md',
'',
'The shortest file in the repo.',
'',
'```',
'To:    jake@stockunlock.com',
'Re:    (three clear sentences about what you\'re building and why)',
'SLA:   One business day, ET',
'```',
'',
'**GitHub:** [github.com/JakeRuth](https://github.com/JakeRuth)  ',
'**Location:** NYC area · open to remote / hybrid  ',
'**Resume:** [official_resume.pdf](../../official_resume.pdf)',
'',
'> [!TIP]',
'> Good subjects: "Founding engineer at a stealth thing," "Senior IC role at something you\'ve heard of," "Just curious — want to grab coffee." Bad subjects: "Synergy opportunity."',
''
].join('\n');

/* ---------- HIRE.md ---------- */
CONTENT.HIRE = [
'# HIRE.md',
'',
'The longer version of [README.md#hire-options](#hire-options).',
'',
'## What I\'m looking for',
'',
'A team I\'d pick, working on something I\'d want my name on, with AI treated as a first-class tool rather than a costume. Brutally honest teammates who disagree directly, with reason. High-bar, get-shit-done culture.',
'',
'## What the work looks like from my side',
'',
'- **Ships production code on day one.** No onboarding curve — just let me loose.',
'- **System design + code review instincts from Oscar years + scaling SU.**',
'- **Founding-range responsibility available.** I\'ve been the senior IC who knows the codebase cold and the CEO who raised a seed. Those two rarely live in the same person.',
'- **AI-forward.** I\'ll write specs, read every diff, and ship more than you\'d expect.',
'',
'## What I won\'t do',
'',
'- Compliment sandwiches in feedback.',
'- Bureaucracy and politics over shipping.',
'- Overcharging for bad software.',
''
].join('\n');

/* ---------- CHANGELOG.md ---------- */
CONTENT.CHANGELOG = [
'# CHANGELOG.md',
'',
'All notable changes to Jake Ruth. Format loosely follows [Keep a Changelog](https://keepachangelog.com/).',
'',
'## [13.0.0] — 2026-04-20',
'',
'### Added',
'- Re-entering-the-workforce status.',
'- AI-assisted Discord ops bot (prod).',
'- Customer.io → AWS SES migration (-$6K/yr).',
'- Webflow marketing rewrite for Stock Unlock.',
'',
'### Changed',
'- Moved Stock Unlock from full-time to key-decisions-only (late 2024).',
'- AI workflow: Claude Code + Codex + CMUX as primary.',
'',
'### Removed',
'- Day-to-day operating role at Stock Unlock.',
'',
'## [12.x] — 2022–2024',
'',
'### Added',
'- YC W22 batch.',
'- $1.335M seed ($500K YC SAFE + $835K other investors).',
'- Scaled team from 3 to 8.',
'- Thousands of paying customers.',
'',
'## [11.x] — 2021',
'',
'### Added',
'- Stock Unlock (co-founded with Daniel Pronk and Nick Puljik).',
'- Left Oscar Health after ~4 years.',
'',
'## [7.x–10.x] — 2017–2021 · Oscar Health',
'',
'- Associate → Mid → Senior.',
'- Declined manager track on purpose.',
'- Built internal chatbot with Peter from hackathon scraps.',
'- Unicycle + Rubik\'s cube at the talent show. Josh Kushner was there.',
'',
'## [3.x–6.x] — 2013–2016 · CommerceHub + Youni',
'',
'- CommerceHub intern → FTE.',
'- Youni (React Native v0.13, shut down).',
'- Took down prod once as an intern. Wasn\'t my fault.',
'',
'## [1.0.0] — 2010',
'',
'### Added',
'- AP Computer Science, taken specifically to avoid AP Calculus.',
'- Fell in love with code in week one.',
''
].join('\n');
