/* All the rendered content for the readme medium.
   Markdown strings for the README chrome + sibling docs.
   Issues + PR data for the Issues/PRs tabs. */

window.CONTENT = {};

/* ---------- README.md ---------- */
CONTENT.README = [
'<div class="readme-hero">',
'  <div class="super">',
'    <span>📦 jake-ruth</span>',
'    <span class="dot-sep">·</span>',
'    <span>updated 2026-04</span>',
'    <span class="dot-sep">·</span>',
'    <span>maintained by <a href="https://github.com/JakeRuth" target="_blank" rel="noopener">@JakeRuth</a></span>',
'  </div>',
'',
'  # Jake Ruth',
'',
'  <div class="tagline">',
'    I commit hard to things with depth. Code and cubes are the two that have held fifteen-plus years.<br/>',
'    Then a senior-year math credit dropped me into AP Computer Science instead of AP Calc, and the loop closed. Fifteen years of shipping later, four companies in (two I worked at, two I started), code is the one that stuck. Cubes too.',
'  </div>',
'</div>',
'',
'<div class="badge-row">',
'  <a class="shield" data-color="orange" href="#stock-unlock"><span class="k">YC</span><span class="v">W22</span></a>',
'  <a class="shield" data-color="blue" href="#overview"><span class="k">based</span><span class="v">NYC</span></a>',
'  <a class="shield" data-color="green" href="#hire-options"><span class="k">status</span><span class="v">open to talk</span></a>',
'  <a class="shield" data-color="purple" href="#philosophy"><span class="k">AI</span><span class="v">driver-seat</span></a>',
'  <a class="shield" data-color="gray" href="#TIMELINE"><span class="k">years shipping</span><span class="v">15</span></a>',
'  <a class="shield" data-color="yellow" href="#hire-options"><span class="k">license</span><span class="v">market rate + equity</span></a>',
'  <a class="shield" data-color="red" href="#mastery"><span class="k">3x3 avg</span><span class="v">13.95s</span></a>',
'</div>',
'',
'<div class="avatar-row">',
'  <div class="avatar">JR</div>',
'  <div>',
'    <div class="handle">@JakeRuth <small>he/him · jake2ruth@gmail.com · NYC area</small></div>',
'  </div>',
'</div>',
'',
'> [!NOTE]',
'> Quiet line, not a banner: open to full-time, contract, or equity-founding conversations.',
'',
'## Overview',
'',
'I write software. I have for fifteen years, across four companies, two I worked at, two I started.',
'',
'Pre-teen me ran lemonade stands often enough that my parents told me to stop, shoveled snow for cash, and dragged my old toys onto the curb for a garage sale around age 11. The lock-in-and-go-deep pattern has been there the whole time. Senior year of high school I needed a math credit, refused AP Calc, and asked Mrs. Nalbandian if her AP Computer Science class counted. She said yes. She ran a function on the board in the first five minutes of the first class. I knew right there.',
'',
'CommerceHub three years (intern → FT, "first real engineering"). Co-founded **Youni**, a college-localized social-media iOS app, with Anthony and Jordan; folded after a few months full-time. Joined **Oscar Health** at ~50 engineers under Alan Warren (the Google leader who scaled Google Docs from 2-3 people to thousands), left at ~150+, declined the team-lead path twice. Co-founded **[Stock Unlock](https://stockunlock.com)**, led the [YC W22](https://www.ycombinator.com/companies/stock-unlock) interview, raised $1.35M seed, scaled to a team of eight and thousands of paying customers. Runs profitably today; three full-time (two engineers + an exec assistant) handle day-to-day; I\'m on key decisions only.',
'',
'> [!TIP]',
'> Open **TIMELINE** in the file tree for the `git log` view. Flip the **Terminal** toggle in the header for the same content with a shell skin.',
'',
'## What\'s in the box',
'',
'- **Fifteen years shipping production code** across CommerceHub, Oscar Health, Youni, and Stock Unlock.',
'- **Founder experience that isn\'t theoretical.** Led a YC interview. Closed a $1.35M seed. Hired a team of eight; grew to and sustained ~3,900 paying customers; right-sized when the math demanded it.',
'- **Full-stack range.** Python, Golang, TypeScript, Java, Groovy/Grails. React since pre-hooks; React Native since v0.13.',
'- **Infra fluency.** AWS (SES, EC2, S3), Docker Compose, Postgres, SRE-adjacent on a custom-hosted analytics integration at Oscar.',
'- **AI-native, done right.** Heavy Claude Code + Codex + CMUX, with my own Open Hands harness on the side. Driver in the seat, not driven by the car. Opus 4.5 in early 2026 was the inflection.',
'- **Culture carrier.** Built Emotiqueue with my coworker Peter at Oscar, a Slack chatbot that became 3,000+ custom emoticons and 50+ commands across the company. Solved a Rubik\'s cube on a unicycle at the talent show. Twice.',
'',
'## Featured Projects',
'',
'<div class="project-grid">',
'  <div class="project-card" data-color="green">',
'    <div class="pc-head">',
'      <span class="pc-name">stock-unlock</span>',
'      <span class="pc-type">SaaS · YC W22</span>',
'    </div>',
'    <div class="pc-body">',
'      Software for retail investors that doesn\'t treat them as marks. Built it. Scaled to eight people and thousands of paying customers. Runs profitably today; three FT (two engineers + an exec assistant) handle day-to-day, I\'m on key decisions.',
'    </div>',
'    <div class="pc-meta">',
'      <span>YC W22</span><span>$1.35M seed</span><span>profitable</span>',
'    </div>',
'  </div>',
'',
'  <div class="project-card" data-color="purple">',
'    <div class="pc-head">',
'      <span class="pc-name">x-poster</span>',
'      <span class="pc-type">self-improving AI agent</span>',
'    </div>',
'    <div class="pc-body">',
'      Drafts X posts with a human-in-the-loop. Bootstrap-trained on thousands of tagged posts; spins up Playwright to grab in-product screenshots; LangChain pipeline pulls human feedback + live engagement and rewrites its own prompt. Probably the most ambitious thing I\'ve built that isn\'t a company.',
'    </div>',
'    <div class="pc-meta"><span>LangChain</span><span>Playwright</span><span>internal</span></div>',
'  </div>',
'',
'  <div class="project-card" data-color="purple">',
'    <div class="pc-head">',
'      <span class="pc-name">emotiqueue</span>',
'      <span class="pc-type">internal Slack bot · Oscar</span>',
'    </div>',
'    <div class="pc-body">',
'      Built with my coworker Peter from a HipChat-emoji hackathon goof. Routed messages through a deliberately ridiculous queue-of-queues + ticketing pipeline back into chat. By the time I left: 3,000+ custom emoticons, 50+ commands, other engineers across the company committing.',
'    </div>',
'    <div class="pc-meta"><span>shipped</span><span>real users</span></div>',
'  </div>',
'',
'  <div class="project-card" data-color="orange">',
'    <div class="pc-head">',
'      <span class="pc-name">customerio-to-ses</span>',
'      <span class="pc-type">infra migration</span>',
'    </div>',
'    <div class="pc-body">',
'      Migrated Stock Unlock off Customer.io to self-hosted AWS SES with custom admin panels. Most of the code came out of Claude Code; I read the parts that mattered (security, deliverability, business logic). One person, one focused weekend.',
'    </div>',
'    <div class="pc-meta"><span>~$5-6K/yr saved</span><span>AI-assisted</span><span>prod</span></div>',
'  </div>',
'',
'  <div class="project-card" data-color="red">',
'    <div class="pc-head">',
'      <span class="pc-name">discord-ops-bot</span>',
'      <span class="pc-type">internal tool</span>',
'    </div>',
'    <div class="pc-body">',
'      Permissioned Discord ops bot on EC2 + Docker Compose. Built so non-technical teammates can query logs, errors, code, and user data in natural language without being able to do anything they shouldn\'t.',
'    </div>',
'    <div class="pc-meta"><span>deployed</span><span>docker-compose</span></div>',
'  </div>',
'',
'  <div class="project-card" data-color="gray">',
'    <div class="pc-head">',
'      <span class="pc-name">marketing-site-rewrite</span>',
'      <span class="pc-type">Webflow → self-hosted</span>',
'    </div>',
'    <div class="pc-body">',
'      Migrated Stock Unlock\'s marketing site off Webflow into a self-hosted codebase we control end-to-end. ~$1K/yr saved, 20x more content pages, full UX control, no more contractors to update copy. Programmatic SEO + GEO pages on top, AI-generated and human-reviewed.',
'    </div>',
'    <div class="pc-meta"><span>20x footprint</span><span>self-hosted</span></div>',
'  </div>',
'',
'  <div class="project-card" data-color="blue">',
'    <div class="pc-head">',
'      <span class="pc-name">blinds-motor</span>',
'      <span class="pc-type">hardware · spare hours</span>',
'    </div>',
'    <div class="pc-body">',
'      First hardware project I\'ve ever attempted. Wirelessly-controlled motor that raises and lowers the blinds in my apartment, Adafruit Feather, a small motor, more circuitry than I fully understood when I started. Codex writes most of the embedded; I learn enough hardware to stay in the seat.',
'    </div>',
'    <div class="pc-meta"><span>Adafruit Feather</span><span>Arduino IDE</span></div>',
'  </div>',
'</div>',
'',
'## Stock Unlock',
'',
'> [!NOTE]',
'> **The honest framing.** Built it. [YC W22](https://www.ycombinator.com/companies/stock-unlock). Scaled to eight people and thousands of paying customers. Runs profitably today. Three full-time (two engineers + an exec assistant) handle day-to-day; I\'m on key decisions only.',
'',
'COVID era, watching Daniel Pronk\'s investing YouTube. He was burning 5-10 hours every weekend on Excel sheets for his videos. I built a Python automation in a weekend that did the same job, faster. Driver was unrelenting curiosity and a nerdy thrill, plus I wanted free access to his paid Discord by being useful.',
'',
'Daniel ignored me for ~6 weeks while I emailed and commented. He eventually replied, to make me stop. First call was over a beer. He let me into the Discord. I dropped an early Excel-generator alpha. Users freaked: *"are you selling this?"* / *"could you add this stock?"* / *"I would pay for this."* That was the moment I knew there was a business in it.',
'',
'Brought **Nick Puljik** over from Oscar. **Y Combinator reached out cold via LinkedIn before we\'d applied.** We applied, got in. I led the YC interview. Closed **$1.35M seed**. Scaled to a team of eight, grew to and sustained ~3,900 paying customers.',
'',
'Hit a ~3,900-paying-subscriber wall in 2024, new sign-ups roughly equaled churn. Tried partial pivots. Bet on a set of big feature launches in late 2025; they took too long, burned the team, and didn\'t land. Right-sized in early 2026. Worked it full-tilt up to that point.',
'',
'Runs profitably today. Three FT (two engineers + an exec assistant) handle day-to-day. I\'m on key decisions and weekend pokes.',
'',
'> The real [Stock Unlock](https://stockunlock.com) brag isn\'t a unicorn outcome, it\'s that the company is alive, profitable, and has thousands of customers who love it. That alone outperforms most [YC W22](https://www.ycombinator.com/companies/stock-unlock) cohort companies.',
'',
'> Core conviction underneath the company: **overcharging for bad software is theft from people who can\'t afford to be robbed.** That conviction was load-bearing for building [Stock Unlock](https://stockunlock.com).',
'',
'Full version: [docs/STOCK_UNLOCK.md](#STOCK_UNLOCK).',
'',
'## Philosophy',
'',
'> Driver in the seat, not driven by the car.',
'',
'AI writes more code than I do. I review every line that matters, business logic, security, system architecture. Cosmetic frontend, let it run. The distinction between vibe coding and software engineering is real; I care about the difference.',
'',
'Tool progression: Copilot ("cool, not life-changing") → Cursor (~1-2 years heavy) → Claude Code dabble through 2025 → **Opus 4.5 in early 2026 was the tidal-wave inflection.** Now on Opus 4.7. Heavy Claude Code + Codex + CMUX (multi-instance Ghostty wrapper). Built my own harness via Open Hands.',
'',
'```python',
'# The pattern, in one function',
'def ship(change):',
'    diff = ai.write(change.spec)',
'    review = human.review(',
'        diff,',
'        attention=["business_logic", "security", "architecture"],',
'    )',
'    if review.green():',
'        return change.ship()',
'    return ship(change.with_feedback(review))',
'```',
'',
'Tool-to-task in daily use: Gemini for maps and search, Grok for current events and snark, Claude for deep thinking, Cursor composer for fast code search. The shift from feeling like a 10x engineer to a 100x engineer is real and recent.',
'',
'> [!TIP]',
'> This site you\'re reading was built 100% with Claude Code, reviewed by me. The whole thing is one pass at the thesis.',
'',
'## Mastery',
'',
'The pattern: I commit hard to things with depth. *Self-improvement as a core operating system part of me.* Cubes and code are the two that have held fifteen-plus years. Both have feedback loops and infinite depth.',
'',
'- **Speed-cubing.** Competed 2008-2014 at Northeast US events and Nationals (WCA-sanctioned). 3×3 average **13.95s**. Top-20 in the US at the Pyraminx at peak. [WCA profile](https://www.worldcubeassociation.org/persons/2008RUTH01).',
'- **Unicycle.** ~12-16 months of intense practice junior year of high school. Mountain unicycle, one-footed, forward and backward, stair jumps. Combined with cubing on stage at Oscar talent shows. Twice.',
'- **Track and field.** Captain and MVP senior year of high school. Jumper events, high jump, triple jump, long jump, plus the 400m and the occasional 4x400.',
'- **Other reps.** JV soccer captain sophomore year. Rugby at UAlbany, came in as a sport newcomer, moved B-squad → A-squad. Indoor rock climbing through the Oscar years (~2 years steady). Skateboarding "very good" as a teenager. DDR + Guitar Hero + RuneScape + Tetris + Minesweeper, obsessively. Math accelerated track since 3rd grade.',
'',
'The flip side of hyperfixation is the inverse signal: without a feedback loop I tune out. Bad student in English and history. A high-school classmate told me once that I was good at everything that didn\'t matter. He wasn\'t wrong. The list above is the list of things I got weirdly good at and then moved past, which is what makes the ones that stuck stick out.',
'',
'## Convictions',
'',
'**For:** brutally honest teammates who disagree directly, with reason, no compliment-sandwiches. Autonomy and real ownership. High-bar teams. Get-shit-done culture. AI as a first-class tool with the human in the seat. Being a culture carrier by default.',
'',
'**Against:** bureaucracy and politics over shipping. PIP-driven theater. Buzzword resumes ("passionate," "results-oriented," "dynamic team player"). "Fisher-Price" software, looks polished, breaks under real use. Overcharging for software that ships people short, especially when the people getting shorted can\'t afford it. Vibe coding sold as software engineering.',
'',
'**Serendipity as a working principle.** Most of what\'s worked for me looks lucky in retrospect. AP CS to dodge AP Calc. The Tekkapalooza resume drop. The Oscar interview question that just happened to match my last project. Daniel replying out of exhaustion. YC reaching out via LinkedIn. The pattern is that luck only finds people who keep running at it.',
'',
'## Hire options',
'',
'> [!NOTE]',
'> Real numbers live over email. Market rate plus equity, against the shape of the actual engagement.',
'',
'| Tier | For | Terms | CTA |',
'|---|---|---|---|',
'| **Full-Time** | Senior IC, founding engineer, or early-stage CTO. | Market rate + equity | [Email Jake](mailto:jake2ruth@gmail.com?subject=Full-time) |',
'| **Equity Founding** | Zero-to-one conviction bets on a problem I\'d care about. | Co-founder track, real equity | [Talk to Jake](mailto:jake2ruth@gmail.com?subject=Founding) |',
'| **Contract** | Defined deliverable, defined timeline. | Contact | [Talk to Jake](mailto:jake2ruth@gmail.com?subject=Contract) |',
'| **Starter conversation** | If you\'re not sure. | Email | [Contact](mailto:jake2ruth@gmail.com?subject=Hello) |',
'',
'I\'ve led a YC interview before; I\'d rather build something that matters than chase a logo. Won\'t manage unless the team is right and the work stays close to the code.',
'',
'## FAQ',
'',
'<details>',
'  <summary><strong>What\'s your role at Stock Unlock now?</strong></summary>',
'  <p>Key decisions and weekend pokes. Three full-time employees, two engineers and an exec assistant, handle day-to-day. The company runs profitably and has thousands of customers who love it. I worked it full-tilt until early 2026.</p>',
'</details>',
'',
'<details>',
'  <summary><strong>What\'s the unicycle cube thing?</strong></summary>',
'  <p>Oscar Health talent show, solved a Rubik\'s cube on a unicycle. Did it twice, two years apart. Had to retrain for the second one; mastery decays fast if you don\'t tend it. Speed-cubing competitively 2008-2014, 3×3 average 13.95s, top-20 in the US at the Pyraminx at peak.</p>',
'</details>',
'',
'<details>',
'  <summary><strong>How do you actually use AI day-to-day?</strong></summary>',
'  <p>Heavy Claude Code + Codex + CMUX (multi-instance Ghostty wrapper), plus a homemade Open Hands harness. Crisp specs, every diff that touches business logic or security gets read, cosmetic frontend runs loose. Recent shipped at Stock Unlock with AI assist: SES migration, marketing-site rewrite, Discord ops bot, programmatic SEO + GEO, code review automation across the team, the X poster (a self-improving social-AI agent with a human-in-the-loop). Including this site you\'re reading.</p>',
'</details>',
'',
'<details>',
'  <summary><strong>Will you manage?</strong></summary>',
'  <p>Only if the team is right and the work stays close to the code. Declined the team-lead path at Oscar twice. Hired and let go gracefully at Stock Unlock. Mentored newer engineers unofficially throughout, getting people up to speed is one of my strengths.</p>',
'</details>',
'',
'<details>',
'  <summary><strong>Remote, hybrid, or onsite?</strong></summary>',
'  <p>NYC area. Onsite NYC, hybrid NYC, or strong-async remote, all good.</p>',
'</details>',
'',
'<details>',
'  <summary><strong>What happened to Youni?</strong></summary>',
'  <p>Co-founded a college-localized social-media iOS app with Anthony (CEO) and Jordan, both UAlbany D1 soccer. React Native v0.13/0.14. Launched at SUNY Albany and Binghamton. 70-person paid-in-credits brand-ambassador program, 20,000+ posts at peak. No business model and an unsolved cold-start. Folded after ~4-5 months full-time. Eyes definitely bigger than my stomach.</p>',
'</details>',
'',
'## Contact',
'',
'<div class="contact-card">',
'  <div class="row"><span class="label">email</span><a href="mailto:jake2ruth@gmail.com">jake2ruth@gmail.com</a></div>',
'  <div class="row"><span class="label">github</span><a href="https://github.com/JakeRuth" target="_blank" rel="noopener">github.com/JakeRuth</a></div>',
'  <div class="row"><span class="label">WCA</span><a href="https://www.worldcubeassociation.org/persons/2008RUTH01" target="_blank" rel="noopener">worldcubeassociation.org/persons/2008RUTH01</a></div>',
'  <div class="row"><span class="label">resume</span><a href="../../../official_resume.pdf" target="_blank" rel="noopener">official_resume.pdf</a></div>',
'  <div class="row"><span class="label">location</span>NYC area · open to remote / hybrid</div>',
'  <div class="row"><span class="label">response</span>Fast during ET business hours. Email over DMs.</div>',
'  <div class="row"><span class="label">as of</span>April 2026 · working on what\'s up next</div>',
'</div>',
'',
'> If you\'re not sure, email me anyway. We\'ll figure out whether it\'s a fit.',
'',
'---',
'',
'<p class="muted" style="text-align:center; font-size:12px;">',
'  README.md · 100% built with Claude Code, reviewed by Jake · ',
'  <a href="#top">back to top</a> · ',
'  <a href="#" id="hint-raw">view source</a>',
'</p>',
''
].join('\n');

/* ---------- ABOUT.md ---------- */
CONTENT.ABOUT = [
'# ABOUT.md',
'',
'The longer-form "who am I" file, for when the README is not enough.',
'',
'## The short story',
'',
'Westchester → Albany → NYC. Fifteen years of shipping. Four companies, two I worked at (CommerceHub, Oscar Health), two I started (Youni, Stock Unlock). Currently working on what\'s up next.',
'',
'## Pre-teen',
'',
'Westchester, NY. Lemonade stands frequent enough that my parents told me to stop. Snow shoveling for cash. Around 11 or 12, ran a mini garage sale of my old toys on the street. Skateboarding, DDR, Guitar Hero, RuneScape, Tetris and Minesweeper on a Windows 95 box. The lock-in-and-go-deep pattern that became the through-line.',
'',
'## High school',
'',
'Accelerated math track since third grade. Trouble focusing in school overall, math, science, and art classes were the only ones I cared about. Was probably headed for a math major because that\'s what I was good at.',
'',
'Started speed-cubing in 2008 (competed through 2014). Started unicycling junior year, 12-16 months of mountain-unicycle, one-footed, trick-grade practice. Track captain and MVP senior year, jumper (high jump, triple jump, long jump), 400m, occasional 4x400. JV soccer captain sophomore year.',
'',
'### The AP CS switch',
'',
'Senior year. Catch-22: my school required seniors to take a math credit, but I\'d burned through every math class except AP Calc. I refused AP Calc.',
'',
'Mrs. Nalbandian, a teacher who liked me but was annoyed I was clearly smart and clearly coasting, mentioned in passing she taught AP Computer Science.',
'',
'I asked: *"Does that count as a math credit?"*  ',
'She said, begrudgingly: *"Yes. Why are you asking?"*  ',
'I said: *"Okay, great. Now I don\'t need to take AP Calc, I\'ll take your computer science class instead."*',
'',
'She had mixed feelings. Took me anyway. She ran a function on the board in the first five minutes of the first class. I knew right there. Fifteen years later, that sideways pivot is still the main road.',
'',
'## SUNY Albany (2011-2015)',
'',
'BS in Computer Science + Applied Mathematics. **Dean\'s List every semester.**',
'',
'Junior year I took over the dying ACM (CS Club). Outgoing seniors had identified me from CS-lounge time and class performance and handed me the presidency. I got professors who liked me to let me announce an interest meeting at the end of their classes. Booked a lecture hall, ~7pm on a weeknight. ~50-100 students showed; few dozen joined. Ran weekly meetings, LAN parties, and workshops on what I was learning at my CommerceHub internship. Two years as president. The club survived past me, which mattered more than the headcount.',
'',
'### Tekkapalooza',
'',
'While running ACM, I organized a club field trip to Tekkapalooza, a regional showcase of Albany-area tech companies. Not framed as a recruiting event. I told members to bring resumes anyway. I handed mine directly to a company called CommerceHub. They liked me enough to offer an interview, in which I told them I really wanted to learn how to code and hopefully it wasn\'t going to be about getting coffee. They laughed, said that\'s only what happens in movies. Three years of internship work plus a full-time role grew out of that one resume drop.',
'',
'Also played rugby briefly (B-squad → A-squad after learning the sport).',
'',
'## CommerceHub (2013-2016, Albany)',
'',
'Intern through senior year of college plus a full-time summer (didn\'t go home), then FT after graduation. Left **exactly one year and seven days** into FT to go full-time on Youni.',
'',
'Stack: Groovy/Grails on the back, early-pre-hooks React on the front, code-review culture, virtual machines for cross-browser testing. The "first real engineering" job. Great mentors. Loved it from the start. Junior software engineer level by graduation.',
'',
'### The IE7 ellipsis',
'',
'Fixed an ellipsis bug in a company-name display string that didn\'t render properly in Internet Explorer 7. QVC was pinned to IE7 in 2014. To test the fix I had to spin up a virtual machine running an old version of Windows just to load the browser. Engineering history is preserved in QVC\'s procurement contracts.',
'',
'### The production takedown',
'',
'I had access to a tool that could take a system in production down with a single button press. I pressed the button. Production went down. Walked into the meeting room nervous, started apologizing before anyone spoke. The manager stood up before I finished and said: *"That wasn\'t your fault, you shouldn\'t have had access to that tool. We\'re not celebrating that this happened, but the system was the problem, not you."* That sentence rewired how I think about systems, access, and blameless culture.',
'',
'### My Plastic Brain (parallel)',
'',
'Several hundred hours of paid contract work in college, parallel to the CH internship, building KineticJS card games for a brain-injury rehab startup called My Plastic Brain. Connected via friend-of-a-friend; client was a mother roughly double my age. Digital adaptations of physical card games that brain-injury rehab patients used in real life. Self-directed end-to-end.',
'',
'## Youni (2015-2017, Albany → Troy)',
'',
'Co-founded a college-localized social-media iOS app with **Anthony** (CEO; ran the ACE entrepreneurship club at SUNY Albany) and **Jordan**, both UAlbany D1 soccer players. Met them via club mixers when ACM and ACE crossed paths. Worked nights and weekends through CommerceHub, then went full-time after CH.',
'',
'React Native v0.13/0.14 plus a simple companion site. Free office space at an accelerator near Troy. A "school-localized Instagram", closed-loop networks per college, with Greek-life and sports-team features. Anthony and Jordan won ~$25K in equity-free business grants while still students. Launched at SUNY Albany and Binghamton. **70-person paid-in-credits brand-ambassador program** (Anthony\'s design, students got school credit for promoting). **20,000+ posts** at peak.',
'',
'No business model and an unsolved cold-start. Folded after ~4-5 months full-time. Eyes definitely bigger than my stomach.',
'',
'## Oscar Health (March 2017 - 2021, NYC)',
'',
'Joined at ~50 engineers under **Alan Warren** (formerly the Google leader who scaled Google Docs from 2-3 people to thousands). That attracted heavy talent: lots of FAANG and Ivy-pedigreed engineers. The bar was visibly higher than CommerceHub. Left at ~150+. Associate → Mid (within a year) → Senior (~2 years later); senior for a year before leaving. Offered the team-lead path twice when I was a senior, declined both times. Mentored newer engineers unofficially throughout, getting people up to speed is one of my strengths.',
'',
'Owned services across Python and Golang back-ends and a React front-end, including the internal site for the hundreds of care-guides and ops staff working out of the Tempe, AZ office. Worked tightly with SRE on a custom-hosted analytics integration. By my senior year I was a go-to engineer across two teams for full-stack questions and just getting stuff shipped.',
'',
'Picked up indoor rock climbing here with friends from the team. Two-ish years of steady climbing, problem-solving with your body, plus social. Would pick it up again in a heartbeat.',
'',
'### The Oscar interview luck',
'',
'Late 2016. Design question: *"if you were going to build a social-media app where people could follow each other, how would you architect it?"* I\'d just spent a year and a half building Youni. I crushed the answer. Years later, I brought it up to my manager. He told me no, it was a standard rotation question, asked at random, by people who hadn\'t read my resume. The single most architecturally similar question they could have asked, asked by chance, on the day that mattered most. That\'s the moment I think about when I try to explain why I believe in serendipity.',
'',
'### Emotiqueue',
'',
'Built with my coworker Peter. Started as a custom-emoticon flood, first in HipChat, then Slack. Hackathon project that routed messages through a deliberately ridiculous pipeline (queues into queues, then a ticketing system, then back into chat) ending in a chatbot. By the time I left it had **3,000+ custom emoticons, 50+ silly entertainment-focused commands**, and a codebase other engineers across the company committed to. Half goof, half real internal tool.',
'',
'### Talent show #1 and #2',
'',
'Crowd loose, half-drunk, having a good time. Hand a Rubik\'s cube to someone in the audience. *"Scramble this."* Ride out from the side on the unicycle. Switch to backwards. Stack chairs and a table from the all-hands room into an obstacle course. Jump across them. Take the cube back. Solve it on the unicycle, as the finale. "All the Small Things" by Blink-182 in the background. People talked about it for weeks.',
'',
'Two years later: encore. Slightly less elaborate; kept the cube-on-unicycle finale. Spent a couple of days outside my apartment before the show re-grinding the basics, mastery decays fast if you don\'t tend it.',
'',
'## [Stock Unlock](https://stockunlock.com) (2021 → present, [YC W22](https://www.ycombinator.com/companies/stock-unlock))',
'',
'See [docs/STOCK_UNLOCK.md](#STOCK_UNLOCK) for the full version.',
'',
'## What I care about',
'',
'- Brutally honest teammates who disagree directly, with reason. No compliment-sandwiches.',
'- Autonomy and real ownership. Things that matter and don\'t sound like bullshit.',
'- High-bar teams. Get-shit-done culture.',
'- AI as a first-class tool, with the human in the seat.',
'- Being a culture carrier by default. Emotiqueue is one example of that energy in action.',
'',
'## What I\'m against',
'',
'- Bureaucracy and politics over shipping. PIP-driven theater.',
'- Buzzword resumes, "passionate," "results-oriented," "dynamic team player."',
'- "Fisher-Price" software, looks polished, breaks under real use.',
'- Overcharging for software that ships people short, especially when the people getting shorted can\'t afford it.',
'- Vibe coding sold as software engineering.',
'',
'## Currently',
'',
'Working on what\'s up next. Open to full-time, contract, or equity-founding conversations.',
''
].join('\n');

/* ---------- STOCK_UNLOCK.md ---------- */
CONTENT.STOCK_UNLOCK = [
'# STOCK_UNLOCK.md',
'',
'The long version of the Stock Unlock story.',
'',
'## Framing',
'',
'> Built it. [YC W22](https://www.ycombinator.com/companies/stock-unlock). Scaled to a team of eight and thousands of paying customers. Runs profitably today. Three full-time (two engineers + an exec assistant) handle day-to-day; I\'m on key decisions only.',
'',
'Read the above twice before reading the rest. It\'s the honest framing.',
'',
'## Origin',
'',
'COVID era. I was watching Daniel Pronk\'s investing YouTube channel. He mentioned spending 5-10 hours every weekend building Excel sheets for his content. I thought: *"Damn, that\'s so dumb. This guy\'s smart. Why is he wasting that time?"*',
'',
'I built a Python automation in a weekend that hit cheap financial APIs and exported the same Excel format he was making by hand. Then I started emailing him. Commenting on his content. Trying to give him the tool for free. Primary driver was unrelenting curiosity and a nerdy thrill, plus I wanted into his paid Discord for free, and being useful felt like the way in.',
'',
'Daniel ignored me for about six weeks. He eventually replied, not because he was sold, but to get me to go away: *"How can I help you?"* Instead of going away, I jumped on a video call, cracked a beer, and we instantly hit it off. He let me into his paid Discord for free. He asked if I could build web apps. I\'d been doing it professionally for six years.',
'',
'## The Discord drop / PMF moment',
'',
'About a thousand members in Daniel\'s paid Discord, behind a YouTube channel of ~100K subscribers at the time. I dropped an early alpha, a basic Excel generator that worked for a handful of stocks. The replies came fast: *"are you selling this?"* / *"could you add this stock?"* / *"I would pay for this."* That\'s the moment I knew there was a business in it.',
'',
'## YC',
'',
'Brought **Nick Puljik** over from Oscar. Y Combinator reached out cold via LinkedIn before we\'d applied. We applied, got in. I led the YC interview.',
'',
'## The raise',
'',
'**$1.35M seed.** Grew to and sustained ~3,900 paying customers.',
'',
'## Scale',
'',
'Scaled to a team of eight and thousands of paying customers.',
'',
'## The wall',
'',
'Hit a ~3,900-paying-subscriber wall in 2024, new sign-ups roughly equaled churn. Tried partial pivots, including B2B sales attempts. Bet on a set of big feature launches in late 2025; they took too long to build, burned the team, and didn\'t land. Right-sized in early 2026. Worked it full-tilt up to that point.',
'',
'## Today',
'',
'- Runs profitably.',
'- Three full-time (two engineers + an exec assistant) handle day-to-day.',
'- I\'m on key decisions and weekend pokes.',
'- Y Combinator W22, alive, profitable, customers love it. Outperforms most of the cohort by being any of those.',
'',
'## The conviction',
'',
'> Overcharging for bad software is theft from people who can\'t afford to be robbed.',
'',
'Overcharging for bad software is theft from people who can\'t afford to be robbed. That conviction was load-bearing for the entire build.',
'',
'## Recent AI-driven work at Stock Unlock',
'',
'- **Customer.io → AWS SES**, self-hosted, with admin panels for broadcasts and campaign config. Saved ~$5-6K/yr. One person, one focused weekend. See [Stories: Customer.io migration](#)',
'- **Webflow → self-hosted marketing site** (post-Opus-4.5). ~$1K/year saved, 20x more content pages, full control of the codebase, no more contractor dependency.',
'- **Programmatic SEO + GEO pages**, AI-generated, human-reviewed.',
'- **The X poster**, self-improving AI agent that drafts X posts, screenshots in-product context via Playwright, queues drafts in an admin UI for human approval, and rewrites its own prompt based on human feedback + live post-performance signals via a LangChain pipeline.',
'- **Permissioned Discord ops bot** on EC2 + Docker Compose, non-technical teammates query logs, errors, code, and user data in natural language.',
'- **Code review automation across the team**, AI reviewing AI, with humans gating the merge.',
''
].join('\n');

/* ---------- PROJECTS.md ---------- */
CONTENT.PROJECTS = [
'# PROJECTS.md',
'',
'The longer-form list. For the short version, see README.md.',
'',
'## [Stock Unlock](https://stockunlock.com), [YC W22](https://www.ycombinator.com/companies/stock-unlock)',
'',
'Co-founded with **Daniel Pronk** and **Nick Puljik**. Closed **$1.35M seed**. Scaled to a team of eight, grew to and sustained ~3,900 paying customers. Runs profitably today; three full-time (two engineers + an exec assistant) handle day-to-day. I\'m on key decisions only.',
'',
'> [Stock Unlock](https://stockunlock.com) exists because a lot of investing software overcharges people who can\'t afford to be robbed. We built something better.',
'',
'Full story: [docs/STOCK_UNLOCK.md](#STOCK_UNLOCK).',
'',
'## The X poster',
'',
'Internal Stock Unlock tool, a self-improving AI agent that drafts X (Twitter) posts with a human-in-the-loop.',
'',
'- Bootstrap-trained on thousands of posts (ours plus competitor accounts) tagged with real engagement metrics, to give it an internal representation of what lands vs. flops.',
'- Aware of every product feature.',
'- Spins up a Playwright browser, authenticates as a real user using our custom test-IDs and front-end attributes, takes in-product screenshots to attach. Error-checks the screenshots before moving on.',
'- Pulls live API data for stats. Queues drafts in an admin UI.',
'- A LangChain pipeline runs a few times a day, pulls human feedback (approvals, denials, edits), and iteratively rewrites the drafter\'s own prompt. A separate cron job watches how live posts actually performed and feeds that back as signal too.',
'',
'Probably the most ambitious thing I\'ve built that isn\'t a company. Driver-in-the-seat made architectural.',
'',
'## Customer.io → AWS SES',
'',
'Migrated Stock Unlock off Customer.io to self-hosted AWS SES with custom admin panels for broadcasts and campaign config, plus the AWS scaffolding around it. Most of the code came out of Claude Code; I read the parts that mattered (security, deliverability, business logic) and shipped. Saved ~$5-6K/year. One person, one focused weekend.',
'',
'## Webflow → self-hosted marketing site',
'',
'Post-Opus-4.5. Migrated us off Webflow into a self-hosted custom codebase, written almost entirely with Claude Code. Direct savings ~$1K/year; bigger wins: no more contractors to update copy (every change is a code change in our own repo), full control over UX patterns Webflow couldn\'t deliver, **20x more content pages.** Programmatic SEO + GEO pages on top, AI-generated and human-reviewed.',
'',
'## Discord ops bot',
'',
'Permissioned internal bot on EC2 via Docker Compose, for non-technical teammates. Read-only by default, audit log routed to a private channel, schema-aware before it writes SQL.',
'',
'## Code review automation',
'',
'AI reviewing AI across the team, with humans gating the merge.',
'',
'## Emotiqueue (Oscar)',
'',
'Built with **Peter** at Oscar. Started as a custom-emoticon flood in HipChat, became a Slack hackathon project that routed messages through queues-into-queues + a ticketing system back into chat. By the time I left: **3,000+ custom emoticons, 50+ silly entertainment-focused commands**, and a codebase other engineers across the company committed to. Half goof, half real internal tool.',
'',
'## The blinds motor',
'',
'First hardware project I\'ve ever attempted. Wirelessly-controlled motor that raises and lowers the blinds in my apartment, Adafruit Feather board, a small motor, more circuitry than I fully understood when I started, all uploaded via the Arduino IDE. Codex writes most of the embedded code; I learn enough of the hardware side to stay in the seat. The fact that I\'m pulling off a domain I\'ve never touched, in spare hours, is part of why I\'m convinced the 10x → 100x shift in engineer output is real and recent.',
'',
'## Youni (shut down)',
'',
'College-localized social-media iOS app on React Native v0.13/0.14, plus a simple companion site. Co-founded with Anthony (CEO) and Jordan, both UAlbany D1 soccer. Launched at SUNY Albany and Binghamton. 70-person paid-in-credits brand-ambassador program. 20,000+ posts at peak. No business model and an unsolved cold-start. Folded after ~4-5 months full-time. Painful in the useful way.',
'',
'## My Plastic Brain (contracting)',
'',
'Several hundred hours of paid contract work in college, parallel to the CommerceHub internship. Built KineticJS card games, digital adaptations of physical card games that brain-injury rehab patients used in real life. Now-defunct company. Self-directed end-to-end.',
''
].join('\n');

/* ---------- HOBBIES.md ---------- */
CONTENT.HOBBIES = [
'# HOBBIES.md',
'',
'Work is only some of it. The pattern: I commit hard to things with depth. Cubes and code are the two that have held fifteen-plus years. Both have feedback loops and infinite depth. *Self-improvement as a core operating system part of me.*',
'',
'## Speed-cubing',
'',
'- Competed 2008-2014 at Northeast US events and Nationals (WCA-sanctioned).',
'- 3×3 average: **13.95 seconds.**',
'- **Top-20 in the US at the Pyraminx** at peak. No longer ranked in any event.',
'- WCA profile: [worldcubeassociation.org/persons/2008RUTH01](https://www.worldcubeassociation.org/persons/2008RUTH01).',
'',
'## Unicycle',
'',
'Started junior year of high school. ~12-16 months of intense practice. Mountain unicycle. One-footed riding. Forward and backward. Stair jumps, mountain-trail riding, bench jumps. Eventually combined with cubing, solved a Rubik\'s cube while riding the unicycle. Did it on stage at an Oscar talent show. **Twice.**',
'',
'## Track and field (high school)',
'',
'Jumper events: high jump, triple jump, long jump. Also ran the 400m and the occasional 4x400. **Captain and MVP senior year** (most points scored on the team). Well-known across the four sectional teams in our area.',
'',
'## Soccer',
'',
'JV captain sophomore year of high school. Didn\'t make varsity.',
'',
'## Rugby',
'',
'UAlbany. Came in as a sport newcomer; moved B-squad → A-squad after learning the game.',
'',
'## Rock climbing',
'',
'Oscar Health era. Indoor, two-ish years of steady climbing with friends from the team. Problem-solving with your body, plus the social side. Would pick it up again in a heartbeat.',
'',
'## Skateboarding',
'',
'Got "very good" as a teenager.',
'',
'## DDR + Guitar Hero + RuneScape',
'',
'Got obsessively good as a teen. Guitar Hero was the cleanest level-progression feedback loop I\'ve ever locked into. Good, not great, but "good" was already past most people. Tetris and Minesweeper on a Windows 95 box round out the early list.',
'',
'## Math',
'',
'Accelerated track since third grade.',
'',
'## Art',
'',
'Actually liked it as a kid; one of the only school subjects outside math/science that held my attention.',
'',
'## Meditation',
'',
'Regular practice as an adult; tied to the serendipity-as-worldview thread.',
'',
'## The inverse signal',
'',
'What I couldn\'t lock in on: anything I didn\'t enjoy. Bad student in English and history class, the classroom register was too dry. I doodled. The flip side of hyperfixation is that without the feedback loop, I tune out.',
'',
'A high school classmate told me once that I was good at everything that didn\'t matter. He wasn\'t wrong. The list above is the list of things I got weirdly good at and then moved past, which is what makes the ones that stuck (cubes, code) stick out.',
''
].join('\n');

/* ---------- CONTACT.md ---------- */
CONTENT.CONTACT = [
'# CONTACT.md',
'',
'The shortest file in the repo.',
'',
'```',
'To:    jake2ruth@gmail.com',
'Re:    (three clear sentences about what you\'re building and why)',
'SLA:   One business day, ET',
'```',
'',
'**GitHub:** [github.com/JakeRuth](https://github.com/JakeRuth)  ',
'**WCA:** [worldcubeassociation.org/persons/2008RUTH01](https://www.worldcubeassociation.org/persons/2008RUTH01)  ',
'**Location:** NYC area · open to remote / hybrid  ',
'**Resume:** [official_resume.pdf](../../../official_resume.pdf)',
'',
'> [!TIP]',
'> If you\'re not sure, email me anyway. We\'ll figure out whether it\'s a fit.',
''
].join('\n');

/* ---------- HIRE.md ---------- */
CONTENT.HIRE = [
'# HIRE.md',
'',
'The longer version of the hire options table in README.md.',
'',
'## What I\'m looking for',
'',
'A team I\'d pick, working on something I\'d want my name on, with AI treated as a first-class tool. Brutally honest teammates who disagree directly, with reason. High-bar, get-shit-done culture. Has to be a problem I\'d care about, I\'ve led a YC interview before; I\'d rather build something that matters than chase a logo.',
'',
'## What the work looks like from my side',
'',
'- **Ships production code on day one.** No onboarding curve, just let me loose.',
'- **System design and code-review instincts** from Oscar years plus scaling Stock Unlock.',
'- **Founding-range responsibility available.** Senior IC who knows the codebase cold *and* the founder who led a YC interview and raised a seed. Those two rarely live in the same person.',
'- **AI-forward.** I\'ll write specs, read every diff that matters, and ship more than you\'d expect.',
'- **Mentorship as a side effect.** Mentored newer engineers unofficially throughout my career, getting people up to speed is one of my strengths.',
'',
'## What I won\'t do',
'',
'- Compliment sandwiches in feedback.',
'- Bureaucracy and politics over shipping.',
'- Overcharging for software that ships people short.',
'- Vibe coding sold as software engineering.',
'',
'## Tiers',
'',
'### Full-Time',
'',
'Senior IC, founding engineer, or early-stage CTO. NYC, hybrid, or strong-async remote. **Market rate plus equity.** Won\'t manage unless the team is right and the work stays close to the code.',
'',
'**CTA:** [Email Jake](mailto:jake2ruth@gmail.com?subject=Full-time%20role)',
'',
'### Equity Founding',
'',
'For zero-to-one conviction bets. Co-founder track with real equity. It has to be a problem I\'d care about.',
'',
'**CTA:** [Talk to Jake](mailto:jake2ruth@gmail.com?subject=Founding%20conversation)',
'',
'### Contract',
'',
'Defined deliverable, defined timeline. Open to this selectively.',
'',
'**CTA:** [Talk to Jake](mailto:jake2ruth@gmail.com?subject=Contract%20engagement)',
'',
'### Starter conversation',
'',
'If you\'re not sure. Email me. We\'ll figure it out.',
'',
'**CTA:** [Contact](mailto:jake2ruth@gmail.com?subject=Hello)',
'',
'## On pricing',
'',
'No specific dollar prices on the site. Real numbers live over email, against the shape of the actual engagement. Market rate plus equity is the frame.',
''
].join('\n');

/* ---------- FAQ.md ---------- */
CONTENT.FAQ = [
'# FAQ.md',
'',
'For the same questions rendered as GitHub-style issues, click the **Issues** tab up top.',
'',
'## What\'s your role at Stock Unlock now?',
'',
'Key decisions and weekend pokes. Three full-time employees, two engineers and an exec assistant, handle day-to-day. The company runs profitably and has thousands of customers who love it. I worked it full-tilt until early 2026.',
'',
'## What\'s your take on AI tools?',
'',
'Driver in the seat, not driven by the car. AI writes more code than I do; human-reviewed where it matters (business logic, security, system architecture); cosmetic frontend runs loose. Opus 4.5 in early 2026 was the inflection point. Heavy Claude Code + Codex + CMUX, plus a homemade Open Hands harness on the side.',
'',
'Tool-to-task in daily use: Gemini for maps and search, Grok for current events and snark, Claude for deep thinking, Cursor composer for fast code search.',
'',
'## Will you manage?',
'',
'Only if the team is right and the work stays close to the code. Declined the team-lead path at Oscar twice. Hired and let go gracefully at Stock Unlock. Mentored newer engineers unofficially throughout, getting people up to speed is one of my strengths.',
'',
'## Remote / hybrid / onsite?',
'',
'NYC area. Onsite NYC, hybrid NYC, or strong-async remote, all good.',
'',
'## Do you still code?',
'',
'Every day. Faster than I ever have, because the tooling finally caught up to the work. Including this site you\'re reading, built 100% with Claude Code, reviewed by me.',
'',
'## What happened to Youni?',
'',
'Co-founded with Anthony (CEO) and Jordan, both UAlbany D1 soccer. React Native v0.13/0.14. Launched at SUNY Albany and Binghamton. 70-person paid-in-credits brand-ambassador program, 20,000+ posts at peak. No business model and an unsolved cold-start. Folded after ~4-5 months full-time. Painful in the useful way, the lessons carried straight into Stock Unlock.',
'',
'## What\'s the unicycle cube thing?',
'',
'Solved a Rubik\'s cube on a unicycle at an Oscar talent show. Did it twice, two years apart. Speed-cubing competitively 2008-2014, 3×3 average 13.95s, top-20 in the US at the Pyraminx at peak.',
'',
'## What does this site say about you that the resume doesn\'t?',
'',
'The README plus TIMELINE plus Issues plus PRs is the actual document.',
''
].join('\n');

/* ---------- CHANGELOG.md ---------- */
CONTENT.CHANGELOG = [
'# CHANGELOG.md',
'',
'All notable changes to Jake Ruth. For the full graph, see TIMELINE.',
'',
'## 2026-04',
'',
'### Added',
'- The blinds motor (first hardware project, Adafruit Feather + Arduino IDE).',
'- This site, built 100% with Claude Code.',
'- Open to full-time, contract, or equity-founding conversations.',
'',
'### Changed',
'- Right-sized Stock Unlock to three FT (two engineers + an exec assistant); moved to key decisions only.',
'- AI workflow: heavy Claude Code + Codex + CMUX, plus a homemade Open Hands harness. Opus 4.7 in the seat.',
'',
'## 2025',
'',
'### Added',
'- Marketing-site rewrite (Webflow → self-hosted, ~$1K/yr, 20x content footprint).',
'- Customer.io → AWS SES migration (~$5-6K/yr saved, one weekend).',
'- The X poster (self-improving social-AI agent with a human-in-the-loop).',
'- Programmatic SEO + GEO pages.',
'- Code review automation across the team.',
'- Permissioned Discord ops bot on EC2 + Docker Compose.',
'',
'### Changed',
'- Opus 4.5 inflection point: 10x → 100x engineer output shift.',
'',
'## 2024',
'',
'### Changed',
'- Hit a ~3,900-paying-subscriber wall at Stock Unlock.',
'',
'## 2022-2023',
'',
'### Added',
'- YC W22 batch.',
'- $1.35M seed. Grew to and sustained ~3,900 paying customers.',
'- Scaled team to eight; thousands of paying customers.',
'',
'## 2021',
'',
'### Added',
'- Stock Unlock co-founded with Daniel Pronk (and Nick Puljik from Oscar).',
'- The Discord drop / PMF moment.',
'- YC reached out cold via LinkedIn.',
'- Left Oscar Health after ~4 years.',
'',
'## 2017-2021 · Oscar Health',
'',
'- Joined under Alan Warren at ~50 engineers; left at ~150+.',
'- Associate → Mid → Senior. Declined the team-lead path twice.',
'- Built Emotiqueue with Peter (3,000+ emoticons, 50+ commands).',
'- Solved a Rubik\'s cube on a unicycle at the talent show. Twice.',
'- Picked up indoor rock climbing.',
'',
'## 2013-2016 · CommerceHub + Youni',
'',
'- CommerceHub intern (via Tekkapalooza resume drop) → FTE.',
'- Took down prod once with a button I shouldn\'t have had access to. Wasn\'t my fault.',
'- IE7 ellipsis bug for QVC, fixed with a Windows VM in 2014.',
'- Co-founded Youni (React Native v0.13/0.14) with Anthony and Jordan.',
'- My Plastic Brain contracting in parallel, KineticJS card games for brain-injury rehab.',
'',
'## 2011-2015 · SUNY Albany',
'',
'- BS CS + Applied Math. Dean\'s List every semester.',
'- Took over the dying ACM (CS Club); ran it two years.',
'',
'## 2011',
'',
'### Added',
'- AP Computer Science, taken specifically to avoid AP Calculus.',
'- Mrs. Nalbandian ran a function on the board in the first five minutes. Loop closed.',
''
].join('\n');

/* ---------- ISSUES (rendered in Issues tab) ---------- */
CONTENT.ISSUES = [
  {
    id: 47,
    title: 'What\'s your role at Stock Unlock now?',
    labels: ['question', 'stock-unlock'],
    author: 'curious-founder',
    opened: '2 days ago',
    comments: 3,
    body:
      "Key decisions and weekend pokes. Three full-time employees, two engineers and an exec assistant, handle day-to-day. " +
      "The company runs profitably and has thousands of customers who love it. I worked it full-tilt until early 2026."
  },
  {
    id: 46,
    title: 'How do you actually use AI day-to-day?',
    labels: ['question', 'ai'],
    author: 'eng-manager',
    opened: '5 days ago',
    comments: 5,
    body:
      "Driver in the seat, not driven by the car. Heavy Claude Code + Codex + CMUX, plus a homemade Open Hands harness. " +
      "Crisp specs, every diff that touches business logic or security gets read, cosmetic frontend runs loose. Opus 4.5 in early 2026 was the inflection. " +
      "Tool-to-task: Gemini for maps and search, Grok for current events and snark, Claude for deep thinking, Cursor composer for fast code search."
  },
  {
    id: 45,
    title: 'Will you manage?',
    labels: ['question', 'role-fit'],
    author: 'hiring-partner',
    opened: '1 week ago',
    comments: 1,
    body:
      "Only if the team is right and the work stays close to the code. Declined the team-lead path at Oscar twice. " +
      "Hired and let go gracefully at Stock Unlock. Mentored newer engineers unofficially throughout, getting people up to speed is one of my strengths."
  },
  {
    id: 44,
    title: 'Is the unicycle cube thing real?',
    labels: ['lore', 'non-blocker'],
    author: 'someone-at-oscar',
    opened: '2 weeks ago',
    comments: 12,
    body:
      "Yes. Oscar Health talent show, solved a Rubik's cube on a unicycle. Did it twice, two years apart. " +
      "Had to retrain for the second one; mastery decays fast if you don't tend it. " +
      "Speed-cubing competitively 2008-2014, 3×3 average 13.95s, top-20 in the US at the Pyraminx at peak."
  },
  {
    id: 43,
    title: 'What happened to Youni?',
    labels: ['question', 'youni'],
    author: 'curious-reader',
    opened: '3 weeks ago',
    comments: 4,
    body:
      "Co-founded with Anthony (CEO) and Jordan, both UAlbany D1 soccer. React Native v0.13/0.14. " +
      "Launched at SUNY Albany and Binghamton. 70-person paid-in-credits brand-ambassador program, 20,000+ posts at peak. " +
      "No business model and an unsolved cold-start. Folded after ~4-5 months full-time. Painful in the useful way."
  }
];

/* ---------- PRS (career events as merged PRs) ---------- */
CONTENT.PRS = [
  {
    id: 28,
    title: 'Open: looking for the next thing',
    state: 'open',
    labels: ['available', 'quiet-line'],
    branch: 'main',
    base: 'main',
    author: 'JakeRuth',
    opened: '2026-04',
    merged: null,
    commits: 1,
    changed: 2,
    additions: 1,
    deletions: 1,
    body:
      "Working on what's up next. Stock Unlock runs profitably without me in the seat day-to-day. " +
      "Open to full-time, contract, or equity-founding conversations. Has to be a problem I'd care about. Reviewers welcome."
  },
  {
    id: 27,
    title: 'Right-size Stock Unlock to three FT; move to key decisions only',
    state: 'merged',
    labels: ['stock-unlock', 'maintenance'],
    branch: 'stock-unlock',
    base: 'main',
    author: 'JakeRuth',
    opened: '2026-01',
    merged: '2026-02',
    commits: 8,
    changed: 12,
    additions: 200,
    deletions: 5,
    body:
      "Hit a ~3,900-paying-subscriber wall in 2024. Late-2025 feature launches took too long, burned the team, didn't land. " +
      "Right-sized in early 2026. Three full-time (two engineers + an exec assistant) handle day-to-day. " +
      "Company runs profitably. Customers love it. Worked it full-tilt up to that point."
  },
  {
    id: 26,
    title: 'Ship Customer.io → SES, Webflow → self-hosted, X poster, Discord ops bot',
    state: 'merged',
    labels: ['stock-unlock', 'AI-assisted', 'shipped'],
    branch: 'ai-era',
    base: 'main',
    author: 'JakeRuth',
    opened: '2025-06',
    merged: '2026-02',
    commits: 14,
    changed: 31,
    additions: 4340,
    deletions: 2900,
    body:
      "Migrated off Customer.io to self-hosted AWS SES (~$5-6K/yr saved, one weekend). " +
      "Migrated marketing site off Webflow to self-hosted (~$1K/yr, 20x content footprint, full UX control). " +
      "Built the X poster, self-improving social-AI agent with a human-in-the-loop, LangChain pipeline. " +
      "Built a permissioned Discord ops bot on EC2 + Docker Compose. Programmatic SEO + GEO pages. Code review automation across the team."
  },
  {
    id: 25,
    title: 'Raise $1.35M seed, scale to a team of eight',
    state: 'merged',
    labels: ['stock-unlock', 'YC-W22'],
    branch: 'stock-unlock',
    base: 'main',
    author: 'JakeRuth',
    opened: '2021-12',
    merged: '2022-01',
    commits: 11,
    changed: 52,
    additions: 4020,
    deletions: 200,
    body:
      "Y Combinator reached out cold via LinkedIn before we'd applied. Applied, got in. Led the YC interview. " +
      "$1.35M seed. Grew to and sustained ~3,900 paying customers. " +
      "Scaled to a team of eight and thousands of paying customers."
  },
  {
    id: 24,
    title: 'Co-found Stock Unlock with Daniel Pronk',
    state: 'merged',
    labels: ['founding', 'merge'],
    branch: 'pronk',
    base: 'stock-unlock',
    author: 'JakeRuth',
    opened: '2021-04',
    merged: '2021-06',
    commits: 11,
    changed: 52,
    additions: 4020,
    deletions: 200,
    body:
      "COVID-era Python automation in a weekend that replaced Daniel's 5-10 hours of weekend Excel work. " +
      "Six weeks of cold emails until he replied, to make me stop. First call was over a beer. He let me into his paid Discord. " +
      "I dropped an early Excel-generator alpha. Users freaked: 'are you selling this?' / 'I would pay for this.' That was the moment I knew there was a business in it. " +
      "Brought Nick Puljik over from Oscar."
  },
  {
    id: 23,
    title: 'Close Youni branch (project ended)',
    state: 'merged',
    labels: ['youni', 'archived'],
    branch: 'youni',
    base: 'main',
    author: 'JakeRuth',
    opened: '2017-01',
    merged: '2017-03',
    commits: 3,
    changed: 48,
    additions: 120,
    deletions: 2300,
    body:
      "Co-founded with Anthony (CEO) and Jordan, both UAlbany D1 soccer. React Native v0.13/0.14. " +
      "Launched at SUNY Albany and Binghamton. 70-person paid-in-credits brand-ambassador program. 20,000+ posts at peak. " +
      "No business model and an unsolved cold-start. Folded after ~4-5 months full-time. Eyes definitely bigger than my stomach. " +
      "Lessons dragged into main."
  }
];

/* ---------- ISSUE LABELS (right rail) ---------- */
CONTENT.ISSUE_LABELS = [
  { name: 'question',     color: '#2f81f7', count: 4 },
  { name: 'stock-unlock', color: '#fe7d37', count: 1 },
  { name: 'ai',           color: '#a371f7', count: 1 },
  { name: 'role-fit',     color: '#d29922', count: 1 },
  { name: 'youni',        color: '#3fb950', count: 1 },
  { name: 'lore',         color: '#f778ba', count: 1 },
  { name: 'non-blocker',  color: '#8d96a0', count: 1 },
];
