/* All the rendered content for the readme medium.
   Markdown strings for the README chrome + sibling docs.
   Issues + PR data for the Issues/PRs tabs. */

window.CONTENT = {};

/* ---------- README.md ---------- */
CONTENT.README = [
'<div class="readme-hero">',
'  <div class="super">',
'    <span>📦 jake-ruth</span>',
'    <span class="dot-sep">·</span>',
'    <span>updated 2026-05</span>',
'    <span class="dot-sep">·</span>',
'    <span>maintained by <a href="https://github.com/JakeRuth" target="_blank" rel="noopener">@JakeRuth</a></span>',
'  </div>',
'',
'  # Jake Ruth',
'',
'  <div class="tagline">',
'    Software engineer for fifteen years. Built <a href="https://stockunlock.com" target="_blank" rel="noopener">Stock Unlock</a> (<a href="https://www.ycombinator.com/companies/stock-unlock" target="_blank" rel="noopener">YC W22</a>). Obsessive hobbyist.',
'  </div>',
'</div>',
'',
'<div class="badge-row">',
'  <a class="shield" data-color="orange" href="#stock-unlock"><span class="k">YC</span><span class="v">W22</span></a>',
'  <a class="shield" data-color="blue" href="#overview"><span class="k">based</span><span class="v">NYC</span></a>',
'  <a class="shield" data-color="green" href="#email"><span class="k">status</span><span class="v">open to talk</span></a>',
'  <a class="shield" data-color="purple" href="#philosophy"><span class="k">AI</span><span class="v">driver-seat</span></a>',
'  <a class="shield" data-color="gray" href="#TIMELINE"><span class="k">years shipping</span><span class="v">15</span></a>',
'  <a class="shield" data-color="yellow" href="#email"><span class="k">license</span><span class="v">market rate + equity</span></a>',
'  <a class="shield" data-color="red" href="#mastery"><span class="k">3x3 avg</span><span class="v">13.95s</span></a>',
'</div>',
'',
'<div class="avatar-row">',
'  <div class="avatar">JR</div>',
'  <div>',
'    <div class="handle">@JakeRuth <small>jake2ruth@gmail.com · NYC area</small></div>',
'  </div>',
'</div>',
'',
'## Overview',
'',
'I built **[Stock Unlock](https://stockunlock.com)** ([YC W22](https://www.ycombinator.com/companies/stock-unlock)), which runs profitably today with a small team. Before that I was a senior engineer at Oscar Health, and my first real engineering job was at CommerceHub.',
'',
'It all started senior year of high school: I refused AP Calc, took Mrs. Nalbandian\'s AP Computer Science instead, and I was hooked in the first five minutes of class. Committing hard to things with depth has been the pattern through my life. Software engineering is the one that stuck.',
'',
'> [!TIP]',
'> Open the **Timeline** tab for the `git log` view. Flip the **Terminal** toggle in the header for the same content with a shell skin.',
'',
'## What\'s in the box',
'',
'- **Fifteen years shipping production code** across CommerceHub, Oscar Health, Youni, and Stock Unlock.',
'- **Founder experience that isn\'t theoretical.** Co-founder, CEO at Stock Unlock. Led the YC interview. Closed a $1.335M seed. Hired a team of eight; grew to and sustained ~3.9k paying customers; right-sized when the math demanded it.',
'- **Full-stack range.** Python, Golang, TypeScript, Groovy/Grails. React since pre-hooks; React Native since v0.13.',
'- **Infra fluency.** AWS (SES, EC2, S3), Docker Compose, Postgres, SRE-adjacent on a custom-hosted analytics integration at Oscar.',
'- **AI-native, done right.** Heavy Claude Code + Codex + CMUX, with my own OpenHands harness on the side. My AI philosophy: *"I drive AI. It doesn\'t drive me."* (yes, like a car). Opus 4.5 in early 2026 was the inflection.',
'- **Culture carrier.** Built Emotiqueue at Oscar, an internal Slack bot. Half goof, half real tool, 3,000+ custom emoticons and 50+ commands and a codebase other engineers across the company committed to. The kind of culture-carrier energy I try to seed wherever I work. Solved a Rubik\'s cube on a unicycle at the talent show. Twice.',
'',
'## Featured Projects',
'',
'<div class="project-grid">',
'  <div class="project-card" data-color="green">',
'    <div class="pc-head">',
'      <span class="pc-name">stock-unlock</span>',
'      <span class="pc-type">SaaS · YC W22</span>',
'    </div>',
'    <div class="pc-body">',
'      Software for retail investors that doesn\'t treat them as marks. Built it. Scaled to eight people and thousands of paying customers. Runs profitably today; a small, lean team handles day-to-day, I\'m on key decisions.',
'    </div>',
'    <div class="pc-meta">',
'      <span>YC W22</span><span>$1.335M seed</span><span>profitable</span>',
'    </div>',
'  </div>',
'',
'  <div class="project-card" data-color="purple">',
'    <div class="pc-head">',
'      <span class="pc-name">x-poster</span>',
'      <span class="pc-type">self-improving AI agent</span>',
'    </div>',
'    <div class="pc-body">',
'      Drafts X posts with a human-in-the-loop. Trained on our own posts (top 50 promoted to few-shot exemplars) plus competitor accounts via the X API, all tagged with full engagement metrics. Playwright grabs in-product screenshots; a LangMem-backed optimizer rewrites the drafter\'s own prompt daily from human feedback and 30-day live engagement, with A/B prompt experiments. Posting is intentionally disabled in code, a human copies approved drafts to X. Probably the most ambitious thing I\'ve built that isn\'t a company.',
'    </div>',
'    <div class="pc-meta"><span>LangChain</span><span>Playwright</span><span>internal</span></div>',
'  </div>',
'',
'  <div class="project-card" data-color="purple">',
'    <div class="pc-head">',
'      <span class="pc-name">emotiqueue</span>',
'      <span class="pc-type">internal Slack bot · Oscar</span>',
'    </div>',
'    <div class="pc-body">',
'      Started as a goof: I kept making custom emoticons for our team chat (HipChat at the time, later Slack). That grew into a hackathon project that routed messages through a deliberately ridiculous queue-of-queues + ticketing pipeline back into chat. By the time I left: 3,000+ custom emoticons, 50+ commands, other engineers across the company committing. Half goof, half real tool, the kind of culture-carrier energy I try to seed wherever I work.',
'    </div>',
'    <div class="pc-meta"><span>shipped</span><span>real users</span></div>',
'  </div>',
'',
'  <div class="project-card" data-color="orange">',
'    <div class="pc-head">',
'      <span class="pc-name">customerio-to-ses</span>',
'      <span class="pc-type">infra migration</span>',
'    </div>',
'    <div class="pc-body">',
'      Migrated Stock Unlock off Customer.io to self-hosted AWS SES. Three send modes (triggered, broadcasts, campaigns), plus a self-serve composer for non-engineers with a "Copy Agent Prompt" button that emits a Claude Code instruction. ~5 min of training and anyone on the team can ship a broadcast. One person, 27 days on the side.',
'    </div>',
'    <div class="pc-meta"><span>~$5-6K/yr saved</span><span>AI-assisted</span><span>prod</span></div>',
'  </div>',
'',
'  <div class="project-card" data-color="red">',
'    <div class="pc-head">',
'      <span class="pc-name">discord-agent</span>',
'      <span class="pc-type">AI coding-and-question agent · Stock Unlock</span>',
'    </div>',
'    <div class="pc-body">',
'      Built on the way out of full-time at Stock Unlock so the small, lean team can ship code and self-serve answers without me in chat day-to-day. <code>/code</code> is end-to-end full-stack engineering on demand: plain-English Discord ask in, GitLab MR out with Playwright screenshots of the change running, code-enforced human-in-the-loop at all critical steps. <code>/ask</code> answers across a dozen-plus read-only data sources (codebase, Aurora, PostHog, Stripe, RevenueCat, Sentry, and more). Two model tiers, Claude Sonnet 4.6 for /code and MiniMax M2.7 for /ask, called via direct Anthropic and MiniMax SDKs (API keys in AWS Secrets Manager). Strict secret isolation: /code-only secrets are deleted on each /ask invocation. Private Discord bot (Discord.py) + OpenHands harness on EC2 + Docker Compose.',
'    </div>',
'    <div class="pc-meta"><span>Discord.py</span><span>OpenHands</span><span>EC2</span><span>Anthropic SDK</span></div>',
'  </div>',
'',
'  <div class="project-card" data-color="gray">',
'    <div class="pc-head">',
'      <span class="pc-name">marketing-site-rewrite</span>',
'      <span class="pc-type">Webflow → self-hosted</span>',
'    </div>',
'    <div class="pc-body">',
'      Migrated Stock Unlock\'s marketing site off Webflow into a self-hosted codebase we control end-to-end. ~$500 to $1K/yr saved in hosting, contractor, and upkeep costs. 20x more content pages, full UX control, no more contractors to update copy. Programmatic SEO + GEO pages on top, AI-generated and human-reviewed.',
'    </div>',
'    <div class="pc-meta"><span>20x footprint</span><span>self-hosted</span></div>',
'  </div>',
'',
'  <div class="project-card" data-color="green">',
'    <div class="pc-head">',
'      <span class="pc-name">jakeruth.com</span>',
'      <span class="pc-type">this site · AI-built, human-reviewed</span>',
'    </div>',
'    <div class="pc-body">',
'      Vanilla HTML/CSS/JS, no build step, three chrome experiences (XP, README, SaaS) sharing a single shell. Hard parity on every fact via shared canonical docs (<code>BACKBONE.md</code> + <code>CLAUDE.md</code>) so any agent reading the codebase stays on-voice. Custom Rubik\'s-cube solver (bidirectional BFS over a compact cubie model) animates the transition between mediums. Written by AI, reviewed by me.',
'    </div>',
'    <div class="pc-meta"><span>three.js</span><span>GitHub Pages</span><span>parity-enforced</span></div>',
'  </div>',
'',
'  <div class="project-card" data-color="blue">',
'    <div class="pc-head">',
'      <span class="pc-name">blinds-motor</span>',
'      <span class="pc-type">hardware · spare hours</span>',
'    </div>',
'    <div class="pc-body">',
'      First hardware project I\'ve ever attempted. Battery-powered, Wi-Fi-controllable motor that pulls the bead chain on the roller shades in my apartment. Bench-prototyping Adafruit Feather ESP32-C6 → DRV8833 → N20 motor over USB; LiPo + MiniBoost battery pass and FixMyBlinds R8 clutch come next. Tried Claude Code first, switched to Codex, which held the depth of conversation I needed for embedded. Early on I was a robotic front-end for Codex; iteration is teaching me the underlying systems.',
'    </div>',
'    <div class="pc-meta"><span>Feather ESP32-C6</span><span>DRV8833</span><span>N20 motor</span><span>Codex</span></div>',
'  </div>',
'</div>',
'',
'## Stock Unlock',
'',
'> [!NOTE]',
'> **The honest framing.** Built it. [YC W22](https://www.ycombinator.com/companies/stock-unlock). Scaled to eight people and thousands of paying customers. Runs profitably today. A small, lean team handles day-to-day; I\'m on key decisions only.',
'',
'COVID era, watching Daniel Pronk\'s investing YouTube. He was burning 5-10 hours every weekend on Excel sheets for his videos. I built a Python automation in a weekend that did the same job, faster. Driver was unrelenting curiosity and a nerdy thrill, plus I wanted free access to his paid Discord by being useful.',
'',
'Daniel ignored me for ~6 weeks while I emailed and commented. He eventually replied, to make me stop. First call was over a beer. He let me into the Discord. I dropped an early Excel-generator alpha. Users freaked: *"are you selling this?"* / *"could you add this stock?"* / *"I would pay for this."* That was the moment I knew there was a business in it.',
'',
'Brought a fellow Oscar engineer with me as the third co-founder. **Y Combinator reached out cold via LinkedIn before we\'d applied.** We applied, got in. I led the YC interview. Closed **$1.335M seed**. Scaled to a team of eight, grew to and sustained ~3.9k paying customers.',
'',
'Sustained ~3.9k paying customers at a profitable, durable steady-state through 2024-2025. Explored adjacent paths to keep growing (partial pivots, a late-2025 feature push). Right-sized in early 2026 around the steady-state. Worked it full-tilt up to that point.',
'',
'Runs profitably today. A small, lean team handles day-to-day. I\'m on key decisions and weekend pokes.',
'',
'> The real [Stock Unlock](https://stockunlock.com) brag isn\'t a unicorn outcome, it\'s that the company is alive, profitable, and has thousands of customers who love it. That alone outperforms most [YC W22](https://www.ycombinator.com/companies/stock-unlock) cohort companies.',
'',
'> Core conviction underneath the company: brokerages profit from trade volume, so they push predatory engagement features over tools that help customers make informed decisions. **Overcharging for bad software is theft from people who can\'t afford to be robbed.** We built [Stock Unlock](https://stockunlock.com) incentivized the right way, subscription revenue only.',
'',
'Full founder story: [stockunlock.com/our-story](https://stockunlock.com/our-story.html). Long version: [docs/STOCK_UNLOCK.md](#STOCK_UNLOCK).',
'',
'## Philosophy',
'',
'> My AI philosophy: *"I drive AI. It doesn\'t drive me."* (yes, like a car)',
'>',
'> *"Two kinds of people use AI. One uses it to skip learning, the other uses it to learn everything. I work hard to be the second."*',
'',
'AI writes more code than I do. I review every line that matters, business logic, security, system architecture. Cosmetic frontend, let it run. The distinction between vibe coding and software engineering is real; I care about the difference.',
'',
'Tool progression: Copilot ("cool, not life-changing") → Cursor (~1-2 years heavy) → Claude Code dabble through 2025 → **Opus 4.5 in early 2026 was the tidal-wave inflection.** Now on Opus 4.7. Heavy Claude Code + Codex + CMUX (a custom Ghostty wrapper). Built my own harness via OpenHands.',
'',
'```python',
'# The pattern, in one function',
'def ship(change):',
'    diff = ai.write(change.spec)',
'    review = human.review(',
'        diff,',
'        attention=["business_logic", "security", "architecture"],',
'    )',
'    if review.green():',
'        return change.ship()',
'    return ship(change.with_feedback(review))',
'```',
'',
'The shift from feeling like a 10x engineer to a 100x engineer is real and recent.',
'',
'> [!TIP]',
'> This site you\'re reading was built 100% with Claude Code, reviewed by me. The whole thing is one pass at the thesis.',
'',
'## Mastery',
'',
'Committing hard to things with depth has been the pattern through my life. Software engineering is the one that stuck. *Self-improvement as a core operating system part of me.*',
'',
'- **Speed-cubing.** Competed 2008-2014 at Northeast US events and Nationals (WCA-sanctioned). 3×3 average **13.95s**. Top-20 in the US at the Pyraminx at peak. [WCA profile](https://www.worldcubeassociation.org/persons/2008RUTH01).',
'- **Unicycle.** ~12-16 months of intense practice junior year of high school. Mountain unicycle, one-footed, forward and backward, stair jumps. Combined with cubing on stage at Oscar Health\'s company talent shows. Twice.',
'- **Track and field.** Captain and MVP senior year of high school. Jumper events, high jump, triple jump, long jump, plus the 400m and the occasional 4x400.',
'- **Other reps.** JV soccer captain sophomore year. Rugby at UAlbany, came in as a sport newcomer, moved B-squad → A-squad. Indoor rock climbing through the Oscar years (~2 years steady). Skateboarding "very good" as a teenager. DDR + Guitar Hero + RuneScape + Tetris + Minesweeper, obsessively. Math accelerated track since 3rd grade.',
'',
'The flip side of hyperfixation is the inverse signal: without a feedback loop I tune out. Bad student in English and history. A high-school classmate told me once that I was good at everything that didn\'t matter. He wasn\'t wrong. The list above is the list of things I got weirdly good at and then moved past, which is what makes the ones that stuck stick out.',
'',
'## Email',
'',
'> [!NOTE]',
'> Real numbers live over email. Market rate plus equity, against the shape of the actual engagement.',
'',
'| Tier | For | Terms | CTA |',
'|---|---|---|---|',
'| **Full-Time** | Senior IC, founding engineer, or early-stage CTO. | Market rate + equity | [Email Jake](mailto:jake2ruth@gmail.com?subject=Full-time) |',
'| **Equity Founding** | Zero-to-one conviction bets on a problem I\'d care about. | Co-founder track, real equity | [Talk to Jake](mailto:jake2ruth@gmail.com?subject=Founding) |',
'| **Contract** | Defined deliverable, defined timeline. | Contact | [Talk to Jake](mailto:jake2ruth@gmail.com?subject=Contract) |',
'| **Starter conversation** | If you\'re not sure. | Email | [Contact](mailto:jake2ruth@gmail.com?subject=Hello) |',
'',
'I\'ve led a YC interview before; I\'d rather build something that matters than chase a logo. Won\'t manage unless the team is right and the work stays close to the code.',
'',
'## FAQ',
'',
'<details>',
'  <summary><strong>What\'s your role at Stock Unlock now?</strong></summary>',
'  <p>Key decisions and weekend pokes. A small, lean team handles day-to-day. The company runs profitably and has thousands of customers who love it. I worked it full-tilt until early 2026.</p>',
'</details>',
'',
'<details>',
'  <summary><strong>What\'s the unicycle cube thing?</strong></summary>',
'  <p>Oscar Health talent show, solved a Rubik\'s cube on a unicycle. Did it twice, two years apart. Had to retrain for the second one; mastery decays fast if you don\'t tend it. Speed-cubing competitively 2008-2014, 3×3 average 13.95s, top-20 in the US at the Pyraminx at peak.</p>',
'</details>',
'',
'<details>',
'  <summary><strong>How do you actually use AI day-to-day?</strong></summary>',
'  <p>Heavy Claude Code + Codex + CMUX (multi-instance Ghostty wrapper), plus a homemade OpenHands harness. Crisp specs, every diff that touches business logic or security gets read, cosmetic frontend runs loose. Recent shipped at Stock Unlock with AI assist: SES migration, marketing-site rewrite, AI coding-and-question agent for the team (Discord-fronted, /code + /ask), programmatic SEO + GEO, code review automation across the team, the X poster (a self-improving social-AI agent with a human-in-the-loop). Including this site you\'re reading.</p>',
'</details>',
'',
'<details>',
'  <summary><strong>Will you manage?</strong></summary>',
'  <p>Only if the team is right and the work stays close to the code. Hired and let go gracefully at Stock Unlock. Mentored newer engineers unofficially throughout, getting people up to speed is one of my strengths.</p>',
'</details>',
'',
'<details>',
'  <summary><strong>Remote, hybrid, or onsite?</strong></summary>',
'  <p>NYC area. Onsite NYC, hybrid NYC, or strong-async remote, all good.</p>',
'</details>',
'',
'<details>',
'  <summary><strong>What happened to Youni?</strong></summary>',
'  <p>Co-founded a college-localized social-media iOS app with two UAlbany D1 soccer players (Anthony, CEO; Jordan). React Native v0.13/0.14. Launched at SUNY Albany and Binghamton. 70-person paid-in-credits brand-ambassador program, 20,000+ posts at peak. No business model and an unsolved cold-start. Folded after ~4-5 months full-time. Eyes definitely bigger than my stomach.</p>',
'</details>',
'',
'## Contact',
'',
'<div class="contact-card">',
'  <div class="row"><span class="label">email</span><a href="mailto:jake2ruth@gmail.com">jake2ruth@gmail.com</a></div>',
'  <div class="row"><span class="label">github</span><a href="https://github.com/JakeRuth" target="_blank" rel="noopener">github.com/JakeRuth</a></div>',
'  <div class="row"><span class="label">WCA</span><a href="https://www.worldcubeassociation.org/persons/2008RUTH01" target="_blank" rel="noopener">worldcubeassociation.org/persons/2008RUTH01</a></div>',
'  <div class="row"><span class="label">resume</span><a href="../../../official_resume.pdf" target="_blank" rel="noopener">official_resume.pdf</a></div>',
'  <div class="row"><span class="label">location</span>NYC area · open to remote / hybrid</div>',
'  <div class="row"><span class="label">response</span>Fast during ET business hours. Email over DMs.</div>',
'  <div class="row"><span class="label">as of</span>April 2026 · working on what\'s up next</div>',
'</div>',
'',
'> If you\'re not sure, email me anyway. We\'ll figure out whether it\'s a fit.',
'',
'---',
'',
'<p class="muted" style="font-size:13px; line-height:1.6;">',
'  <em>Made it to the bottom?</em> A working principle of mine: most of what\'s worked for me looks lucky in retrospect. AP CS to dodge AP Calc. The Tekkapalooza resume drop. The Oscar interview question. Daniel replying out of exhaustion. YC reaching out via LinkedIn. The pattern is that luck only lands on people who keep running at it. Not sure if you\'re into that worldview, but I\'ll shoot my shot, this is something I believe in.',
'</p>',
'',
'<p class="muted" style="text-align:center; font-size:12px;">',
'  README.md · 100% built with Claude Code, reviewed by Jake · ',
'  <a href="#top">back to top</a> · ',
'  <a href="#" id="hint-raw">view source</a>',
'</p>',
''
].join('\n');

/* ---------- ABOUT.md ---------- */
CONTENT.ABOUT = [
'# ABOUT.md',
'',
'The longer-form "who am I" file, for when the README is not enough.',
'',
'## The short story',
'',
'Fifteen years of shipping. Four companies, two I worked at (CommerceHub, Oscar Health), two I started (Youni, Stock Unlock). Currently working on what\'s up next.',
'',
'## Pre-teen',
'',
'Westchester, NY. Lemonade stands frequent enough that my parents told me to stop. Snow shoveling for cash. Around 11 or 12, ran a mini garage sale of my old toys on the street. The lock-in-and-go-deep pattern was already there before any career existed, same intensity that later showed up in skateboarding, DDR, Guitar Hero, and RuneScape.',
'',
'## High school',
'',
'Accelerated math track since third grade.',
'',
'Started speed-cubing in 2008 (competed through 2014). Started unicycling junior year, 12-16 months of mountain-unicycle, one-footed, trick-grade practice. Track captain and MVP senior year, jumper (high jump, triple jump, long jump), 400m, occasional 4x400. JV soccer captain sophomore year.',
'',
'### The AP CS switch',
'',
'Senior year. Catch-22: my school required seniors to take a math credit, but I\'d burned through every math class except AP Calc. I refused AP Calc.',
'',
'Mrs. Nalbandian, a teacher who liked me but was annoyed I was clearly smart and clearly coasting, mentioned in passing she taught AP Computer Science.',
'',
'I asked: *"Does that count as a math credit?"*  ',
'She said, begrudgingly: *"Yes. Why are you asking?"*  ',
'I said: *"Okay, great. Now I don\'t need to take AP Calc, I\'ll take your computer science class instead."*',
'',
'She had mixed feelings. Took me anyway. She ran a function on the board in the first five minutes of the first class. I knew right there. Fifteen years later, that sideways pivot is still the main road.',
'',
'## SUNY Albany (2011 - May 2015)',
'',
'BS in Computer Science + Applied Mathematics. **Dean\'s List every semester.**',
'',
'Junior year I took over the dying ACM (CS Club). Outgoing seniors had identified me from CS-lounge time and class performance and handed me the presidency. I got professors who liked me to let me announce an interest meeting at the end of their classes. Booked a lecture hall, ~7pm on a weeknight. ~50-100 students showed; few dozen joined. Ran weekly meetings, LAN parties, and workshops on what I was learning at my CommerceHub internship. Two years as president. The club survived past me, which mattered more than the headcount.',
'',
'Also Teaching Assistant in the CS department 2013-14: weekly office hours, grading exams and projects.',
'',
'### The moving-van summers',
'',
'Two summers as a mover at Barr Brothers Moving Company in NYC, between freshman/sophomore and sophomore/junior year of college (summers 2012, 2013). Five to six days a week, up to 80 hours, 100% humidity in the sun. You learn fast that you can\'t drop a heavy thing even when your hands are slipping, because it isn\'t yours. Set the work-ethic floor and made the case for college sharper; the not-dropping lesson has cashed in on engineering work plenty since.',
'',
'### Tekkapalooza',
'',
'While running ACM, I organized a club field trip to Tekkapalooza, a regional showcase of Albany-area tech companies. Not framed as a recruiting event. I told members to bring resumes anyway. I handed mine directly to a company called CommerceHub. They liked me enough to offer an interview, in which I told them I really wanted to learn how to code and hopefully it wasn\'t going to be about getting coffee. They laughed, said that\'s only what happens in movies. Three years of internship work plus a full-time role grew out of that one resume drop.',
'',
'Also played rugby briefly (B-squad → A-squad after learning the sport).',
'',
'## CommerceHub (Nov 2013 - July 2016, Albany)',
'',
'**Software Engineer Intern: Nov 2013 - May 2015.** Got the internship junior year via the Tekkapalooza resume drop (a regional Albany-area tech showcase). Part-time fall and spring semesters, full-time summers (didn\'t go home for the senior-year summer).',
'',
'**Associate Software Engineer: July 1, 2015 - July 7, 2016.** Full-time after graduation. Agile team of ~10 engineers, micro-service architecture, on the interview squad (graded offsite submissions, conducted interviews). Left **exactly one year and seven days** into FT to go full-time on Youni.',
'',
'Stack: Groovy/Grails on the back, early-pre-hooks React on the front, code-review culture, virtual machines for cross-browser testing. The "first real engineering" job. Great mentors. Loved it from the start.',
'',
'### The IE7 ellipsis',
'',
'Fixed an ellipsis bug in a company-name display string that didn\'t render properly in Internet Explorer 7. QVC, one of CommerceHub\'s customers, was pinned to IE7 in 2014. To test the fix I had to spin up a virtual machine running an old version of Windows just to load the browser. Engineering history is preserved in QVC\'s procurement contracts.',
'',
'### The production takedown',
'',
'I had admin access to our Apache Solr cluster, the search index powering parts of the production site. Thought I was clicking around in the dev environment; cleared a Solr core. Turned out I was in production. The site went down. Big deal. Walked into the retrospective nervous, started apologizing before anyone spoke. The manager stood up before I finished and said: *"That wasn\'t your fault, you shouldn\'t have had access to that tool. We\'re not celebrating that this happened, but the system was the problem, not you."* That sentence rewired how I think about systems, access, and blameless culture.',
'',
'### My Plastic Brain (parallel to CommerceHub, ~senior year)',
'',
'Paid contract web-game work in college for a now-defunct company called My Plastic Brain. Connected via friend-of-a-friend; client was a mother roughly double my age. **Dozens of simple HTML5 web games (JavaScript, jQuery, KineticJS)**, digital adaptations of physical card games that brain-injury rehab patients used in real life. Handled my own billing, built the client side end-to-end, handed off the deliverables myself. Recruited and trained another contractor as the workload grew. Self-directed start to finish.',
'',
'## Youni (Late 2014 - Nov 2016, Albany → Troy)',
'',
'Co-founded a college-localized social-media iOS app with two UAlbany D1 soccer players (**Anthony**, CEO; **Jordan**). I met Anthony through the ACE entrepreneurship club he ran at SUNY Albany, while I was running ACM. **Co-founder, CTO.** Started nights and weekends late 2014 alongside the CommerceHub internship, ramped up over my last few months at CommerceHub, went **full-time July 2016** after I left CommerceHub.',
'',
'React Native v0.13/0.14 plus a simple companion site. Free office space at an accelerator near Troy. A "school-localized Instagram", closed-loop networks per college, with Greek-life and sports-team features. Anthony and Jordan won ~$25K in equity-free business grants while still students. Launched at SUNY Albany and Binghamton. **70-person paid-in-credits brand-ambassador program** (Anthony\'s design, students got school credit for promoting). **20,000+ posts** at peak.',
'',
'No business model and an unsolved cold-start. Folded after ~4-5 months full-time. Eyes definitely bigger than my stomach.',
'',
'## Oscar Health (March 2017 - 2021, NYC)',
'',
'Joined at \\~50 engineers under **Alan Warren** (formerly the Google leader who scaled Google Docs from 2-3 people to thousands). Left at \\~150+. Associate Software Engineer → Mid (within a year) → **Senior Software Engineer** (\\~2 years later); Senior SWE for a year before leaving. Mentored newer engineers unofficially throughout, getting people up to speed is one of my strengths.',
'',
'Owned a portfolio of back-end services in Python and Golang plus a React front-end. One of those was the internal site for the hundreds of care-guides and ops staff working out of the Tempe, AZ office. Worked tightly with SRE on a custom-hosted analytics integration. By my Senior year I was a go-to engineer across two teams for full-stack questions and just getting stuff shipped.',
'',
'Picked up indoor rock climbing here with friends from the team. Two-ish years of steady climbing, problem-solving with your body, plus social. Would pick it up again in a heartbeat.',
'',
'Left Oscar in 2021 to co-found Stock Unlock full-time.',
'',
'### Ready for the question that came',
'',
'Late 2016. Design question: *"if you were going to build a social-media app where people could follow each other, how would you architect it?"* I\'d just spent eighteen months building Youni. I crushed the answer. Years later, my manager told me it was a standard rotation question, asked at random, by people who hadn\'t read my resume. The catch was random; the prep wasn\'t. The single most architecturally similar question they could have asked, asked by chance, on the day my eighteen months of work had me fully ready for it. That\'s what serendipity actually means: luck only lands on the prepared.',
'',
'### Emotiqueue',
'',
'Started as a goof: I kept making custom emoticons for our team chat (HipChat at the time, later Slack after the company switched tools). That habit grew into a hackathon project that routed messages through a deliberately ridiculous pipeline (queues into queues, then a ticketing system, then back into chat) ending in a chatbot. By the time I left it had **3,000+ custom emoticons, 50+ silly entertainment-focused commands**, and a codebase other engineers across the company committed to. Half goof, half real internal tool, the kind of culture-carrier energy I try to seed wherever I work.',
'',
'### The unicycle cube (twice)',
'',
'Crowd loose, half-drunk, having a good time. Hand a Rubik\'s cube to someone in the audience. *"Scramble this."* Ride out from the side on the unicycle. Switch to backwards. Stack chairs and a table from the all-hands room into an obstacle course. Jump across them. Take the cube back. Solve it on the unicycle, as the finale. "All the Small Things" by Blink-182 in the background. People talked about it for weeks.',
'',
'Two years later: encore. Slightly less elaborate; kept the cube-on-unicycle finale. Spent a couple of days outside my apartment before the show re-grinding the basics, mastery decays fast if you don\'t tend it.',
'',
'## [Stock Unlock](https://stockunlock.com) (2021 → present, [YC W22](https://www.ycombinator.com/companies/stock-unlock))',
'',
'See [docs/STOCK_UNLOCK.md](#STOCK_UNLOCK) for the full version.',
'',
'## Currently',
'',
'Working on what\'s up next. Open to full-time, contract, or equity-founding conversations.',
''
].join('\n');

/* ---------- STOCK_UNLOCK.md ---------- */
CONTENT.STOCK_UNLOCK = [
'# STOCK_UNLOCK.md',
'',
'The long version of the Stock Unlock story.',
'',
'## Framing',
'',
'> Built it. [YC W22](https://www.ycombinator.com/companies/stock-unlock). Scaled to a team of eight and thousands of paying customers. Runs profitably today. A small, lean team handles day-to-day; I\'m on key decisions only.',
'',
'Read the above twice before reading the rest. It\'s the honest framing.',
'',
'## Origin',
'',
'COVID era. I was watching Daniel Pronk\'s investing YouTube channel. He mentioned spending 5-10 hours every weekend building Excel sheets for his content. I thought: *"Damn, that\'s so dumb. This guy\'s smart. Why is he wasting that time?"*',
'',
'I built a Python automation in a weekend that hit cheap financial APIs and exported the same Excel format he was making by hand. Then I started emailing him. Commenting on his content. Trying to give him the tool for free. Primary driver was unrelenting curiosity and a nerdy thrill, plus I wanted into his paid Discord for free, and being useful felt like the way in.',
'',
'Daniel ignored me for about six weeks. He eventually replied, not because he was sold, but to get me to go away: *"How can I help you?"* Instead of going away, I jumped on a video call, cracked a beer, and we instantly hit it off. He let me into his paid Discord for free. He asked if I could build web apps. I\'d been doing it professionally for six years.',
'',
'## The Discord drop / PMF moment',
'',
'About a thousand members in Daniel\'s paid Discord, behind a YouTube channel of ~100K subscribers at the time. I dropped an early alpha, a basic Excel generator that worked for a handful of stocks. The replies came fast: *"are you selling this?"* / *"could you add this stock?"* / *"I would pay for this."* That\'s the moment I knew there was a business in it.',
'',
'## YC',
'',
'Brought a fellow Oscar engineer with me as the third co-founder. Y Combinator reached out cold via LinkedIn before we\'d applied. We applied, got in. I led the YC interview.',
'',
'## The raise',
'',
'**$1.335M seed.** Grew to and sustained ~3.9k paying customers.',
'',
'## Scale',
'',
'Scaled to a team of eight and thousands of paying customers.',
'',
'## Steady-state',
'',
'Sustained ~3.9k paying customers at a profitable, durable steady-state through 2024-2025. Explored adjacent paths to keep growing, including partial pivots and B2B motions. Made a heavy late-2025 feature push, then right-sized in early 2026 around the steady-state. Worked it full-tilt up to that point.',
'',
'## Today',
'',
'- Runs profitably.',
'- A small, lean team handles day-to-day.',
'- I\'m on key decisions and weekend pokes.',
'- Y Combinator W22, alive, profitable, customers love it. Outperforms most of the cohort by being any of those.',
'',
'## The conviction',
'',
'> Overcharging for bad software is theft from people who can\'t afford to be robbed.',
'',
'Brokerages profit from trade volume, so they push predatory engagement features over tools that help customers make informed decisions. Overcharging for bad software is theft from people who can\'t afford to be robbed. We built Stock Unlock incentivized the right way, subscription revenue only. That conviction was load-bearing for the entire build.',
'',
'Full founder story on the Stock Unlock site: [stockunlock.com/our-story](https://stockunlock.com/our-story.html).',
'',
'## Recent AI-driven work at Stock Unlock',
'',
'- **Customer.io → AWS SES**, self-hosted, with admin panels for broadcasts and campaign config. Saved ~$5-6K/yr. One person, 27 days on the side. See [Stories: Customer.io migration](#)',
'- **Webflow → self-hosted marketing site.** Every line written by Claude Code, every commit reviewed by me. ~$500 to $1K/year saved in hosting, contractor, and upkeep costs. 20x more content pages, full control of the codebase, no more contractor dependency.',
'- **Programmatic SEO + GEO pages**, AI-generated, human-reviewed.',
'- **The X poster**, self-improving AI agent that drafts X posts, screenshots in-product context via Playwright, queues drafts in an admin UI for human approval, and rewrites its own prompt based on human feedback + live post-performance signals via a LangChain pipeline.',
'- **AI coding-and-question agent for the team** (Discord-fronted), built as off-boarding gift. `/code` opens GitLab MRs with Playwright screenshots, `/ask` answers across a dozen-plus read-only data sources. Two model tiers (Claude Sonnet 4.6 + MiniMax M2.7) via direct Anthropic and MiniMax SDKs, strict secret isolation between commands.',
''
].join('\n');

/* ---------- PROJECTS.md ---------- */
CONTENT.PROJECTS = [
'# PROJECTS.md',
'',
'The longer-form list. For the short version, see README.md.',
'',
'## [Stock Unlock](https://stockunlock.com), [YC W22](https://www.ycombinator.com/companies/stock-unlock)',
'',
'Co-founded with **Daniel Pronk** and a third co-founder (a fellow engineer from Oscar). **Co-founder, CEO.** Closed **$1.335M seed**. Scaled to a team of eight, grew to and sustained ~3.9k paying customers. Runs profitably today; a small, lean team handles day-to-day. I\'m on key decisions only.',
'',
'> [Stock Unlock](https://stockunlock.com) exists because a lot of investing software overcharges people who can\'t afford to be robbed. We built something better.',
'',
'Full story: [docs/STOCK_UNLOCK.md](#STOCK_UNLOCK).',
'',
'## The X poster',
'',
'Internal Stock Unlock tool, a self-improving AI agent that drafts X (Twitter) posts with a human-in-the-loop.',
'',
'- **Trained on real posts:** ingests Stock Unlock\'s own account plus competitor accounts via the X API. Top 50 of our posts become few-shot exemplars; the rest seed pattern signal. Every post tagged with full engagement metrics (reach, likes, retweets, replies, quotes, bookmarks).',
'- **LangGraph pipeline:** ideate, generate, fact-check, screenshot, quality-gate, save, with conditional retry on failure.',
'- **Self-improving prompt loop:** daily LangMem-backed optimizer ingests human edit-pair preferences, rejection reasons, approval commentary, and 30-day live engagement. Rewrites the system prompt, refreshes the few-shot library, and runs A/B prompt experiments that auto-promote winners and retire underperformers.',
'- **In-product evidence:** Playwright authenticates as a real user, takes attribute-targeted in-product screenshots, error-checks them; live API calls embed real stats.',
'- **Human-in-the-loop:** custom React admin ("Social Station") for review, edit, and publish-mark. Posting itself is intentionally disabled in code; approved drafts live in the DB and a human copies them to X.',
'',
'Probably the most ambitious thing I\'ve built that isn\'t a company. Driver-in-the-seat made architectural.',
'',
'## Customer.io → AWS SES',
'',
'Migrated Stock Unlock off Customer.io to self-hosted AWS SES with three send modes (triggered, broadcasts, scheduled campaigns), plus the AWS scaffolding around it. Built a self-serve composer for non-engineers (three-button UI, live preview, locked design areas). The composer\'s "Copy Agent Prompt" button copies a guided Q&A script into Claude Code that walks the user through the email\'s purpose, audience, and structure, then hands back finished HTML to paste in. Bounces, complaints, and unsubscribes auto-route to the SES suppression list. FastAPI admin endpoints run on AWS Fargate; send-mode workers run on Lambda. Most of the code came out of Claude Code; I read the parts that mattered (security, deliverability, business logic) and shipped. Saved ~$5-6K/year. Hundreds of thousands of emails per month, over a million a year. One person, 27 days on the side.',
'',
'## Webflow → self-hosted marketing site',
'',
'Migrated us off Webflow into a self-hosted custom codebase. Every line written by Claude Code, every commit reviewed by me. Direct savings ~$500 to $1K/year in hosting, contractor, and upkeep costs; bigger wins: no more contractors to update copy (every change is a code change in our own repo), full control over UX patterns Webflow couldn\'t deliver, **20x more content pages.** Programmatic SEO + GEO pages on top, AI-generated and human-reviewed.',
'',
'## AI coding-and-question agent for the team',
'',
'Built on the way out of full-time at Stock Unlock so the small, lean team can ship code changes and answer their own questions without needing me in chat day-to-day. Private Discord bot (Discord.py) on EC2 + Docker Compose, calling an OpenHands harness with source-level patches.',
'',
'`/code` is end-to-end full-stack engineering on demand: takes a plain-English ask in Discord, plans the change, writes the code (frontend, backend, or infra), opens a GitLab MR, attaches Playwright screenshots of the change running so a reviewer sees visual proof alongside the diff. Code-enforced human-in-the-loop at all critical steps.',
'',
'`/ask` answers across a dozen-plus read-only data sources: codebase, Aurora, PostHog, Stripe, RevenueCat, Sentry, plus Finnhub, Finchat, Google Analytics, CloudWatch, S3, and Cognito.',
'',
'Two model tiers, Claude Sonnet 4.6 for `/code` and MiniMax M2.7 for `/ask`, called via direct Anthropic and MiniMax SDKs (API keys in AWS Secrets Manager). Strict secret isolation: `/code`-only secrets are deleted on each `/ask` invocation so a question-answering agent cannot modify production resources, even if a previous `/code` session left credentials in the workspace. SQLite task tracking with orphan-conversation reconciliation; thread-aware UX so multiple people can run jobs in parallel.',
'',
'## Emotiqueue (Oscar)',
'',
'Built at Oscar. Started as a goof: I kept making custom emoticons for our team chat (HipChat at the time, later Slack). That grew into a hackathon project that routed messages through queues-into-queues + a ticketing system back into chat. By the time I left: **3,000+ custom emoticons, 50+ silly entertainment-focused commands**, and a codebase other engineers across the company committed to. Half goof, half real internal tool, the kind of culture-carrier energy I try to seed wherever I work.',
'',
'## This site, jakeruth.com',
'',
'Vanilla HTML/CSS/JS, no build step, three chrome experiences (XP, README, SaaS) sharing a single shell. AI-built, human-reviewed.',
'',
'- **Three mediums, one set of facts.** XP, README, and SaaS share canonical content via `BACKBONE.md` + `CLAUDE.md` in the repo, so any agent reading the codebase stays on-voice and parity holds across mediums.',
'- **Custom Rubik\'s-cube solver.** Bidirectional BFS over a compact cubie model computes the shortest move sequence between any two cube states; animates the transition between mediums.',
'- **Stack.** HTML, CSS, vanilla JS, Three.js. Hosted on GitHub Pages.',
'',
'## The blinds motor',
'',
'First hardware project I\'ve ever attempted. Battery-powered, Wi-Fi-controllable motor that pulls the bead chain on the roller shades in my apartment. Bench-prototyping the Adafruit Feather ESP32-C6 → DRV8833 driver → N20 motor (6V, 1:100, magnetic encoder) chain over USB; LiPo 3.7V + MiniBoost (TPS61023) battery pass and the FixMyBlinds Rollease R8 clutch coupler come next.\n\nTried Claude Code first, switched to Codex. For embedded work (voltage, motor torque, gear ratios, datasheet reading, board pinouts), Codex held the depth of conversation I needed for this project. Long Codex sessions plan the next step; I go bench-test it. Early on I was effectively a robotic front-end for Codex, copying instructions and observing what happened. With iteration I\'m picking up the underlying systems, voltage, current, motor drivers, encoder feedback, LiPo + boost-converter behavior, and starting to ask better questions instead of just relaying. Pulling off a domain I\'ve never touched, in spare hours, is part of why I\'m convinced the 10x → 100x shift in engineer output is real and recent.',
'',
'## Youni (shut down)',
'',
'College-localized social-media iOS app on React Native v0.13/0.14, plus a simple companion site. Co-founded with two UAlbany D1 soccer players (Anthony, CEO; Jordan). Launched at SUNY Albany and Binghamton. 70-person paid-in-credits brand-ambassador program. 20,000+ posts at peak. No business model and an unsolved cold-start. Folded after ~4-5 months full-time. Painful in the useful way.',
'',
'## My Plastic Brain (contracting)',
'',
'Paid contract web-game work in college for a now-defunct company called My Plastic Brain. **Dozens of simple HTML5 web games (JavaScript, jQuery, KineticJS)**, digital adaptations of physical card games that brain-injury rehab patients used in real life. Handled my own billing, built the client side end-to-end, handed off the deliverables myself. Recruited and trained another contractor as the workload grew. Self-directed start to finish.',
''
].join('\n');

/* ---------- HOBBIES.md ---------- */
CONTENT.HOBBIES = [
'# HOBBIES.md',
'',
'Work is only some of it. Committing hard to things with depth has been the pattern through my life. Software engineering is the one that stuck. *Self-improvement as a core operating system part of me.*',
'',
'## Speed-cubing',
'',
'- Competed 2008-2014 at Northeast US events and Nationals (WCA-sanctioned).',
'- 3×3 average: **13.95 seconds.**',
'- **Top-20 in the US at the Pyraminx** at peak.',
'- WCA profile: [worldcubeassociation.org/persons/2008RUTH01](https://www.worldcubeassociation.org/persons/2008RUTH01).',
'',
'## Unicycle',
'',
'Started junior year of high school. ~12-16 months of intense practice. Mountain unicycle. One-footed riding. Forward and backward. Stair jumps, mountain-trail riding, bench jumps. Eventually combined with cubing, solved a Rubik\'s cube while riding the unicycle. Did it on stage at Oscar Health\'s company talent show. **Twice.**',
'',
'## Track and field (high school)',
'',
'Jumper events: high jump, triple jump, long jump. Also ran the 400m and the occasional 4x400. **Captain and MVP senior year** (most points scored on the team). Well-known across the four sectional teams in our area.',
'',
'## Soccer',
'',
'Played all four years of high school. JV captain sophomore year. Started on the varsity team senior year.',
'',
'## Rugby',
'',
'UAlbany. Came in as a sport newcomer; moved B-squad → A-squad after learning the game.',
'',
'## Rock climbing',
'',
'Oscar Health era. Indoor, two-ish years of steady climbing with friends from the team. Problem-solving with your body, plus the social side. Would pick it up again in a heartbeat.',
'',
'## Skateboarding + DDR + Guitar Hero + RuneScape',
'',
'Insanely good at DDR and Guitar Hero, very good at skateboarding, deep on RuneScape. The lock-in pattern was already showing.',
'',
'## Math',
'',
'Skipped onto the accelerated track in third grade and stayed ahead through senior year of high school, burning through every available math class except AP Calc.',
'',
'## Meditation',
'',
'In and out of the practice as an adult but generally enjoy meditating. Also into books on the subconscious mind, plus territory that borders on spirituality, Buddhism, and quantum-philosophy.',
'',
'## The inverse signal',
'',
'What I couldn\'t lock in on: anything I didn\'t enjoy. Bad student in English and history class, the classroom register was too dry. I doodled. The flip side of hyperfixation is that without the feedback loop, I tune out.',
'',
'A high school classmate told me once that I was good at everything that didn\'t matter. He wasn\'t wrong. The list above is the list of things I got weirdly good at and then moved past, which is what makes the ones that stuck (cubes, code) stick out.',
''
].join('\n');

/* ---------- CONTACT.md ---------- */
CONTENT.CONTACT = [
'# CONTACT.md',
'',
'The shortest file in the repo.',
'',
'```',
'To:    jake2ruth@gmail.com',
'Re:    (three clear sentences about what you\'re building and why)',
'SLA:   One business day, ET',
'```',
'',
'**GitHub:** [github.com/JakeRuth](https://github.com/JakeRuth)  ',
'**WCA:** [worldcubeassociation.org/persons/2008RUTH01](https://www.worldcubeassociation.org/persons/2008RUTH01)  ',
'**Location:** NYC area · open to remote / hybrid  ',
'**Resume:** [official_resume.pdf](../../../official_resume.pdf)',
'',
'> [!TIP]',
'> If you\'re not sure, email me anyway. We\'ll figure out whether it\'s a fit.',
''
].join('\n');

/* ---------- CHANGELOG.md ---------- */
CONTENT.CHANGELOG = [
'# CHANGELOG.md',
'',
'All notable changes to Jake Ruth. For the full graph, see TIMELINE.',
'',
'## 2026-04',
'',
'### Added',
'- The blinds motor (first hardware project; Feather ESP32-C6 + DRV8833 + N20 motor; tried Claude Code, switched to Codex for embedded depth).',
'- This site, built 100% with Claude Code.',
'- Open to full-time, contract, or equity-founding conversations.',
'',
'### Changed',
'- Right-sized Stock Unlock to a small, lean team; moved to key decisions only.',
'- AI workflow: heavy Claude Code + Codex + CMUX, plus a homemade OpenHands harness. Opus 4.7 in the seat.',
'',
'## 2025',
'',
'### Added',
'- Marketing-site rewrite (Webflow → self-hosted, ~$500 to $1K/yr saved in hosting/contractor/upkeep, 20x content footprint).',
'- Customer.io → AWS SES migration (~$5-6K/yr saved, 27 days on the side).',
'- The X poster (self-improving social-AI agent with a human-in-the-loop).',
'- Programmatic SEO + GEO pages.',
'- Code review automation across the team.',
'- AI coding-and-question agent for the team (Discord-fronted, /code + /ask, two model tiers (Claude Sonnet 4.6 + MiniMax M2.7) via direct Anthropic and MiniMax SDKs, strict secret isolation).',
'',
'### Changed',
'- Opus 4.5 inflection point: 10x → 100x engineer output shift.',
'',
'## 2024',
'',
'### Changed',
'- Sustained ~3.9k paying customers at Stock Unlock at a profitable, durable steady-state; explored adjacent paths to keep growing.',
'',
'## 2022-2023',
'',
'### Added',
'- YC W22 batch.',
'- $1.335M seed. Grew to and sustained ~3.9k paying customers.',
'- Scaled team to eight; thousands of paying customers.',
'',
'## 2021',
'',
'### Added',
'- Stock Unlock co-founded with Daniel Pronk (plus a third co-founder, a fellow Oscar engineer).',
'- The Discord drop / PMF moment.',
'- YC reached out cold via LinkedIn.',
'- Left Oscar Health after ~4 years.',
'',
'## 2017-2021 · Oscar Health',
'',
'- Joined under Alan Warren at ~50 engineers; left at ~150+.',
'- Associate → Mid → Senior Software Engineer.',
'- Built Emotiqueue at Oscar (3,000+ emoticons, 50+ commands, the kind of culture-carrier energy I try to seed wherever I work).',
'- Solved a Rubik\'s cube on a unicycle at the talent show. Twice.',
'- Picked up indoor rock climbing.',
'',
'## 2013-2016 · CommerceHub + Youni',
'',
'- CommerceHub intern (via Tekkapalooza resume drop) → FTE.',
'- Took down prod once with a button I shouldn\'t have had access to. Wasn\'t my fault.',
'- IE7 ellipsis bug for QVC (a CommerceHub customer), fixed with a Windows VM in 2014.',
'- Co-founded Youni (React Native v0.13/0.14) with two UAlbany D1 soccer players (Anthony, CEO; Jordan).',
'- My Plastic Brain contracting (college era), JavaScript/jQuery/KineticJS web games for brain-injury rehab.',
'',
'## 2011-2015 · SUNY Albany',
'',
'- BS CS + Applied Math. Dean\'s List every semester.',
'- Took over the dying ACM (CS Club); ran it two years.',
'',
'## 2011',
'',
'### Added',
'- AP Computer Science, taken specifically to avoid AP Calculus.',
'- Mrs. Nalbandian ran a function on the board in the first five minutes. Loop closed.',
''
].join('\n');

/* ---------- ISSUES (rendered in Issues tab) ---------- */
CONTENT.ISSUES = [
  {
    id: 47,
    title: 'What\'s your role at Stock Unlock now?',
    labels: ['question', 'stock-unlock'],
    author: 'curious-founder',
    opened: '2 days ago',
    comments: 3,
    body:
      "Key decisions and weekend pokes. A small, lean team handles day-to-day. " +
      "The company runs profitably and has thousands of customers who love it. I worked it full-tilt until early 2026."
  },
  {
    id: 46,
    title: 'How do you actually use AI day-to-day?',
    labels: ['question', 'ai'],
    author: 'eng-manager',
    opened: '5 days ago',
    comments: 5,
    body:
      "My AI philosophy: \"I drive AI. It doesn't drive me.\" (yes, like a car). " +
      "Code is code, hand-written or AI-written, what matters is that it's correct, secure, built to spec, and read where it matters. Vibe coding isn't software engineering. " +
      "Current AI tool stack (as of May 4, 2026): CMUX (a custom Ghostty wrapper) for terminal AI work, invoking Claude Code primarily and Codex situationally. Lighter Cursor / Gemini / Grok use. Constantly reassessing tool fit as the space evolves. " +
      "Opus 4.5 in early 2026 was the inflection."
  },
  {
    id: 45,
    title: 'Will you manage?',
    labels: ['question', 'role-fit'],
    author: 'hiring-partner',
    opened: '1 week ago',
    comments: 1,
    body:
      "Only if the team is right and the work stays close to the code. " +
      "Hired and let go gracefully at Stock Unlock. Mentored newer engineers unofficially throughout, getting people up to speed is one of my strengths."
  },
  {
    id: 44,
    title: 'Is the unicycle cube thing real?',
    labels: ['lore', 'non-blocker'],
    author: 'someone-at-oscar',
    opened: '2 weeks ago',
    comments: 12,
    body:
      "Yes. Oscar Health talent show, solved a Rubik's cube on a unicycle. Did it twice, two years apart. " +
      "Had to retrain for the second one; mastery decays fast if you don't tend it. " +
      "Speed-cubing competitively 2008-2014, 3×3 average 13.95s, top-20 in the US at the Pyraminx at peak."
  },
  {
    id: 43,
    title: 'What happened to Youni?',
    labels: ['question', 'youni'],
    author: 'curious-reader',
    opened: '3 weeks ago',
    comments: 4,
    body:
      "Co-founded with two UAlbany D1 soccer players (Anthony, CEO; Jordan). React Native v0.13/0.14. " +
      "Launched at SUNY Albany and Binghamton. 70-person paid-in-credits brand-ambassador program, 20,000+ posts at peak. " +
      "No business model and an unsolved cold-start. Folded after ~4-5 months full-time. Painful in the useful way."
  }
];

/* ---------- PRS (career events as merged PRs) ---------- */
CONTENT.PRS = [
  {
    id: 28,
    title: 'Open: looking for the next thing',
    state: 'open',
    labels: ['available', 'quiet-line'],
    branch: 'main',
    base: 'main',
    author: 'JakeRuth',
    opened: '2026-04',
    merged: null,
    commits: 1,
    changed: 2,
    additions: 1,
    deletions: 1,
    body:
      "Working on what's up next. Stock Unlock runs profitably without me in the seat day-to-day. " +
      "Open to full-time, contract, or equity-founding conversations. Has to be a problem I'd care about. Reviewers welcome."
  },
  {
    id: 27,
    title: 'Right-size Stock Unlock to a lean team; move to key decisions only',
    state: 'merged',
    labels: ['stock-unlock', 'maintenance'],
    branch: 'stock-unlock',
    base: 'main',
    author: 'JakeRuth',
    opened: '2026-01',
    merged: '2026-02',
    commits: 8,
    changed: 12,
    additions: 200,
    deletions: 5,
    body:
      "Sustained ~3.9k paying customers at a profitable, durable steady-state. Late-2025 feature push, then a decision to right-size. " +
      "Right-sized in early 2026. A small, lean team handles day-to-day. " +
      "Company runs profitably. Customers love it. Worked it full-tilt up to that point."
  },
  {
    id: 26,
    title: 'Ship Customer.io → SES, Webflow → self-hosted, X poster, AI coding-and-question agent',
    state: 'merged',
    labels: ['stock-unlock', 'AI-assisted', 'shipped'],
    branch: 'ai-era',
    base: 'main',
    author: 'JakeRuth',
    opened: '2025-06',
    merged: '2026-02',
    commits: 14,
    changed: 31,
    additions: 4340,
    deletions: 2900,
    body:
      "Migrated off Customer.io to self-hosted AWS SES (~$5-6K/yr saved, 27 days on the side). " +
      "Migrated marketing site off Webflow to self-hosted (~$500 to $1K/yr saved in hosting/contractor/upkeep, 20x content footprint, full UX control). " +
      "Built the X poster, self-improving social-AI agent with a human-in-the-loop, LangChain pipeline. " +
      "Built an AI coding-and-question agent for the team (Discord-fronted): /code opens GitLab MRs with Playwright screenshots, /ask answers across a dozen-plus read-only data sources, two model tiers (Claude Sonnet 4.6 + MiniMax M2.7) via direct Anthropic and MiniMax SDKs, strict secret isolation. Programmatic SEO + GEO pages. Code review automation across the team."
  },
  {
    id: 25,
    title: 'Raise $1.335M seed, scale to a team of eight',
    state: 'merged',
    labels: ['stock-unlock', 'YC-W22'],
    branch: 'stock-unlock',
    base: 'main',
    author: 'JakeRuth',
    opened: '2021-12',
    merged: '2022-01',
    commits: 11,
    changed: 52,
    additions: 4020,
    deletions: 200,
    body:
      "Y Combinator reached out cold via LinkedIn before we'd applied. Applied, got in. Led the YC interview. " +
      "$1.335M seed. Grew to and sustained ~3.9k paying customers. " +
      "Scaled to a team of eight and thousands of paying customers."
  },
  {
    id: 24,
    title: 'Co-found Stock Unlock with Daniel Pronk',
    state: 'merged',
    labels: ['founding', 'merge'],
    branch: 'pronk',
    base: 'stock-unlock',
    author: 'JakeRuth',
    opened: '2021-04',
    merged: '2021-06',
    commits: 11,
    changed: 52,
    additions: 4020,
    deletions: 200,
    body:
      "COVID-era Python automation in a weekend that replaced Daniel's 5-10 hours of weekend Excel work. " +
      "Six weeks of cold emails until he replied, to make me stop. First call was over a beer. He let me into his paid Discord. " +
      "I dropped an early Excel-generator alpha. Users freaked: 'are you selling this?' / 'I would pay for this.' That was the moment I knew there was a business in it. " +
      "Brought a fellow Oscar engineer with me as the third co-founder."
  },
  {
    id: 23,
    title: 'Close Youni branch (project ended)',
    state: 'merged',
    labels: ['youni', 'archived'],
    branch: 'youni',
    base: 'main',
    author: 'JakeRuth',
    opened: '2017-01',
    merged: '2017-03',
    commits: 3,
    changed: 48,
    additions: 120,
    deletions: 2300,
    body:
      "Co-founded with two UAlbany D1 soccer players (Anthony, CEO; Jordan). React Native v0.13/0.14. " +
      "Launched at SUNY Albany and Binghamton. 70-person paid-in-credits brand-ambassador program. 20,000+ posts at peak. " +
      "No business model and an unsolved cold-start. Folded after ~4-5 months full-time. Eyes definitely bigger than my stomach. " +
      "Lessons dragged into main."
  }
];

/* ---------- ISSUE LABELS (right rail) ---------- */
CONTENT.ISSUE_LABELS = [
  { name: 'question',     color: '#2f81f7', count: 4 },
  { name: 'stock-unlock', color: '#fe7d37', count: 1 },
  { name: 'ai',           color: '#a371f7', count: 1 },
  { name: 'role-fit',     color: '#d29922', count: 1 },
  { name: 'youni',        color: '#3fb950', count: 1 },
  { name: 'lore',         color: '#f778ba', count: 1 },
  { name: 'non-blocker',  color: '#8d96a0', count: 1 },
];
