/* All the rendered content for the readme medium.
   Markdown strings for the README chrome + sibling docs.
   Every sentence is sourced from the XP page (the canonical
   reference). Slight rewordings exist only for the markdown
   medium and are matched in voice to /xp/. */

window.CONTENT = {};

/* =====================================================================
   README.md  ·  the main file. Mirrors /xp/ section-for-section:
   hero, About + sysprops, Work history, Recent AI projects, Mastery,
   bottom note. Stories live in the Timeline tab.
   ===================================================================== */
CONTENT.README = [
'<div class="readme-hero">',
'  <div class="super">',
'    <span>📦 jake-ruth</span>',
'    <span class="dot-sep">·</span>',
'    <span>updated 2026-05</span>',
'    <span class="dot-sep">·</span>',
'    <span>maintained by <a href="https://github.com/JakeRuth" target="_blank" rel="noopener">@JakeRuth</a></span>',
'  </div>',
'',
'  # Jake Ruth',
'',
'  <div class="tagline">',
'    Software engineer for fifteen years. Built <a href="https://stockunlock.com" target="_blank" rel="noopener">Stock Unlock</a> (<a href="https://www.ycombinator.com/companies/stock-unlock" target="_blank" rel="noopener">YC W22</a>). Obsessive hobbyist.',
'  </div>',
'  <p class="hero-foot">On the hunt for what\'s next.</p>',
'</div>',
'',
'<div class="badge-row">',
'  <a class="shield" data-color="orange" href="#stock-unlock"><span class="k">YC</span><span class="v">W22</span></a>',
'  <a class="shield" data-color="gray" href="#about"><span class="k">years shipping</span><span class="v">15</span></a>',
'  <a class="shield" data-color="red" href="#mastery-hobbies"><span class="k">3x3 avg</span><span class="v">13.95s</span></a>',
'  <a class="shield" data-color="purple" href="#recent-ai-projects-post-opus-45"><span class="k">AI</span><span class="v">driver-seat</span></a>',
'  <a class="shield" data-color="blue" href="#about"><span class="k">based</span><span class="v">NYC area</span></a>',
'  <a class="shield" data-color="green" href="https://github.com/JakeRuth" target="_blank" rel="noopener"><span class="k">github</span><span class="v">@JakeRuth</span></a>',
'</div>',
'',
'<div class="avatar-row">',
'  <div class="avatar">JR</div>',
'  <div>',
'    <div class="handle">@JakeRuth <small><a href="mailto:jake2ruth@gmail.com">jake2ruth@gmail.com</a> · NYC area</small></div>',
'  </div>',
'</div>',
'',
'## About',
'',
'I built **[Stock Unlock](https://stockunlock.com)** ([YC W22](https://www.ycombinator.com/companies/stock-unlock)), which runs profitable today with a small team. Before that I was a senior engineer at Oscar Health, and my first real engineering job was at CommerceHub. It all started senior year of high school: I refused AP Calc, took Mrs. Nalbandian\'s AP Computer Science instead, and I was hooked in the first five minutes of class. Committing hard to things with depth has been the pattern through my life. Software engineering is the one that stuck.',
'',
'<dl class="sysprops-md">',
'  <div><dt>Name</dt><dd>Jake Ruth</dd></div>',
'  <div><dt>Based</dt><dd>NYC area</dd></div>',
'  <div><dt>Built</dt><dd><a href="https://stockunlock.com" target="_blank" rel="noopener">Stock Unlock</a> (<a href="https://www.ycombinator.com/companies/stock-unlock" target="_blank" rel="noopener">YC W22</a>, 2021 – 2026) · Youni (co-founded late 2014 – Nov 2016)</dd></div>',
'  <div><dt>Worked at</dt><dd>Oscar Health (Senior Software Engineer, March 2017 – 2021) · CommerceHub (intern → Associate SWE, Nov 2013 – July 2016)</dd></div>',
'  <div><dt>Schooled at</dt><dd>SUNY Albany, BS CS + Applied Mathematics</dd></div>',
'  <div><dt>Cubes</dt><dd>WCA (World Cube Association) 2008–2014 · 13.95s 3×3 avg · top-20 US Pyraminx at peak</dd></div>',
'  <div><dt>Notable</dt><dd>Solved a Rubik\'s cube on a unicycle at Oscar Health\'s company talent show. Twice.</dd></div>',
'</dl>',
'',
'> [!TIP]',
'> Open the **Timeline** tab for the `git log` view of moments that mattered.',
'',
'## Work history',
'',
'<p class="md-hint">Click any row to read more. One open at a time.</p>',
'',
'<details id="stock-unlock" class="work-collapse" open>',
'  <summary><strong><a href="https://stockunlock.com" target="_blank" rel="noopener">Stock Unlock</a> · Co-founder, CEO</strong> <span class="muted">2021–2026</span></summary>',
'',
'Built [Stock Unlock](https://stockunlock.com). **[YC Winter 2022.](https://www.ycombinator.com/companies/stock-unlock)** Scaled to a team of eight, raised **$1.335M seed**, grew to and sustained **~3.9k paying customers**. I led the YC interview.',
'',
'Origin: COVID era, watching Daniel Pronk\'s investing YouTube. He was burning 5–10 hours every weekend on Excel sheets for his videos. I wrote a Python automation in a weekend to replace it. Primary driver was unrelenting curiosity and a nerdy thrill (plus I wanted into his paid Discord for free, and being useful felt like the way in). Hounded Daniel for six weeks until he replied to make me stop. First call was over a beer. Brought a fellow Oscar engineer with me as the third co-founder. YC reached out cold via LinkedIn before we\'d even applied.',
'',
'The business is stable, profitable, and customers love it. What we built is a healthy SaaS company that runs without me in the seat day-to-day. **Right-sized in early 2026** to a small, lean team. I\'m on key decisions and weekend pokes.',
'',
'**Core conviction underneath the company:** brokerages profit from trade volume, so they push predatory engagement features over tools that help customers make informed decisions. Overcharging for bad software is theft from people who can\'t afford to be robbed. We built [Stock Unlock](https://stockunlock.com) incentivized the right way, subscription revenue only. The real brag isn\'t a unicorn outcome, it\'s that the company is alive, profitable, and has thousands of customers who love it.',
'',
'<div class="kv-panel">',
'  <div class="kv-title">📊 Build log</div>',
'  <div class="kv"><span>YC Batch</span><strong>Winter 2022</strong></div>',
'  <div class="kv"><span>Raised</span><strong>$1.335M seed</strong></div>',
'  <div class="kv"><span>Subscribers</span><strong>~3.9k sustained</strong></div>',
'  <div class="kv"><span>Peak team</span><strong>8</strong></div>',
'  <div class="kv"><span>P&amp;L</span><strong class="ok">Profitable</strong></div>',
'  <div class="kv"><span>My role</span><strong>Key decisions only</strong></div>',
'</div>',
'',
'<p class="md-fineprint">Full founder story on the <a href="https://stockunlock.com/our-story.html" target="_blank" rel="noopener">Stock Unlock site</a>. Origin and AI-era moments live on the <a href="#TIMELINE">Stories timeline</a>.</p>',
'',
'</details>',
'',
'<details class="work-collapse">',
'  <summary><strong>Oscar Health · Associate → Mid → Senior Software Engineer</strong> <span class="muted">March 2017 – 2021, NYC</span></summary>',
'',
'Joined at ~50 engineers under Alan Warren (formerly scaled Google Docs from 2–3 people to thousands); left at 150+. No formal levels initially; leveled in as Associate Software Engineer, promoted to Mid within ~1 year, **Senior Software Engineer** ~2 years later, Senior SWE for a year before leaving. Owned a portfolio of back-end services in Python and Golang plus a React front-end. One of those was the entire internal site for the hundreds of care-guides and ops staff in the Tempe office. SRE-adjacent on a custom-hosted analytics integration. Built **Emotiqueue**, the internal Slack bot. Half goof, half real tool, the kind of culture-carrier energy I try to seed wherever I work. Mentored newer engineers unofficially throughout. Left in 2021 to co-found [Stock Unlock](https://stockunlock.com) full-time.',
'',
'<p class="md-fineprint">The interview question, Emotiqueue, the talent shows: <a href="#TIMELINE">Stories timeline</a>.</p>',
'',
'</details>',
'',
'<details class="work-collapse">',
'  <summary><strong>Youni · Co-founder, CTO</strong> <span class="muted">Late 2014 – Nov 2016, Albany → Troy</span></summary>',
'',
'Co-founded a college-localized social iOS app with two UAlbany D1 soccer players (**Anthony**, CEO; **Jordan**). I met Anthony through the ACE entrepreneurship club he ran at SUNY Albany, while I was running ACM. React Native v0.13/0.14 with a simple companion site, built out of free accelerator space in Troy. Anthony and Jordan won ~$25K in equity-free business grants while still in school. Launched at SUNY Albany and SUNY Binghamton, ran a 70-person paid-in-credits brand-ambassador program, hit 20,000+ posts at peak. Started on the side late 2014 alongside CommerceHub, ramped up over my last few months there, full-time July to Nov 2016. No business model, unsolved cold-start, folded after ~4 to 5 months full-time.',
'',
'</details>',
'',
'<details class="work-collapse">',
'  <summary><strong>My Plastic Brain · Contractor</strong> <span class="muted">~2014 – 2015, parallel to CommerceHub</span></summary>',
'',
'Dozens of simple HTML5 web games (JavaScript, jQuery, KineticJS), digital adaptations of physical card games used by brain-injury rehab patients. Handled my own billing, built the client side end-to-end, handed off the deliverables myself. Recruited and trained another contractor as the workload grew. Self-directed start to finish.',
'',
'</details>',
'',
'<details class="work-collapse">',
'  <summary><strong>CommerceHub · Intern → Associate Software Engineer</strong> <span class="muted">Nov 2013 – July 2016, Albany</span></summary>',
'',
'Got the internship junior year of college (part-time fall/spring, full-time summers; didn\'t go home for the senior-year summer), then full-time after graduation as an Associate Software Engineer. Agile team of ~10 engineers, micro-service architecture, on the interview squad. Groovy/Grails on the back, early-pre-hooks React on the front, code-review culture, virtual machines for cross-browser testing. "First real engineering." Took down production once with a button I shouldn\'t have had access to. The manager\'s response, that the system was the problem and not the intern, rewired how I think about access and blameless culture. Left exactly one year and seven days into FT to go full-time on Youni.',
'',
'<p class="md-fineprint">The production takedown and the IE7 ellipsis are in the <a href="#TIMELINE">Stories timeline</a>.</p>',
'',
'</details>',
'',
'<details class="work-collapse">',
'  <summary><strong>SUNY Albany · BS Computer Science + Applied Mathematics</strong> <span class="muted">2011 – May 2015</span></summary>',
'',
'**Dean\'s List every semester.** ACM (CS Club) president for two years; took over a dying club, recruited dozens at a lecture-hall pitch, ran weekly meetings, LAN parties, and workshops. Teaching Assistant in the CS department 2013–14 (weekly office hours, graded exams and projects). Organized the Tekkapalooza field trip (a regional Albany-area tech showcase) on behalf of the club, which landed me the CommerceHub internship via direct resume drop. Briefly played rugby (B-squad → A-squad after learning the sport).',
'',
'<p class="md-fineprint">ACM revival and Tekkapalooza are in the <a href="#TIMELINE">Stories timeline</a>.</p>',
'',
'</details>',
'',
'## Recent AI projects · post-Opus 4.5',
'',
'<div class="aiv-lead">',
'  <div class="aiv-label">My AI philosophy:</div>',
'  <p class="aiv-quote"><em>"I drive AI. It doesn\'t drive me."</em> <span class="aiv-aside">(yes, like a car)</span></p>',
'  <p class="aiv-quote"><em>"Two kinds of people use AI. One uses it to skip learning, the other uses it to learn everything. I work hard to be the second."</em></p>',
'</div>',
'',
'1. **Code is code.** Hand-written or AI-written, I want the same thing: correct, secure, built to spec, read by a human where it matters.',
'2. **Vibe coding isn\'t software engineering.** The distinction is real. I care about it.',
'3. **Current AI tool stack (as of May 4, 2026):** CMUX (a custom Ghostty wrapper) for terminal AI work, invoking Claude Code primarily and Codex situationally. Built my own harness via OpenHands. Lighter Cursor / Gemini / Grok use. Constantly reassessing tool fit as the space evolves.',
'',
'<p class="md-hint">Click any row to read more. One open at a time.</p>',
'',
'<details class="work-collapse">',
'  <summary><strong>The X poster · self-improving social agent</strong> <span class="muted"><a href="https://stockunlock.com" target="_blank" rel="noopener">Stock Unlock</a> internal</span></summary>',
'',
'Self-improving X-content agent. Drafts, learns from human feedback and live engagement, queues every post for human approval. Nothing posts without me.',
'',
'- **Trained on real posts:** ingests Stock Unlock\'s own account plus competitor accounts via the X API. Top 50 of our posts become few-shot exemplars; the rest seed pattern signal. Every post tagged with full engagement metrics (reach, likes, retweets, replies, quotes, bookmarks) so the model learns what actually lands.',
'- **LangGraph pipeline:** ideate, generate, fact-check, screenshot, quality-gate, save, with conditional retry on failure.',
'- **Self-improving prompt loop:** daily LangMem-backed optimizer ingests human edit-pair preferences, rejection reasons, approval commentary, and 30-day live engagement. Rewrites the system prompt, refreshes the few-shot library, and flags experiment posts that beat or trail baseline engagement as promote/retire candidates for human review.',
'- **In-product evidence:** Playwright authenticates as a real user, takes attribute-targeted in-product screenshots, error-checks them; live API calls embed real stats.',
'- **Human-in-the-loop:** custom React admin ("Social Station") for review, edit, and publish-mark. Posting itself is intentionally disabled in code, approved drafts live in the DB and a human copies them to X.',
'',
'<div class="md-stack">',
'  <div class="md-stack-row"><span class="md-stack-label">Backend</span><span class="md-stack-chips"><span>Python</span><span>LangChain</span><span>LangGraph</span><span>LangMem</span><span>Tweepy</span><span>Playwright</span></span></div>',
'  <div class="md-stack-row"><span class="md-stack-label">AWS</span><span class="md-stack-chips"><span>Fargate</span><span>Aurora (Postgres)</span><span>S3</span><span>Secrets Manager</span></span></div>',
'  <div class="md-stack-row"><span class="md-stack-label">Frontend</span><span class="md-stack-chips"><span>TypeScript</span><span>React</span><span>MUI</span></span></div>',
'</div>',
'',
'</details>',
'',
'<details class="work-collapse">',
'  <summary><strong>AI coding-and-question agent for the team</strong> <span class="muted"><a href="https://stockunlock.com" target="_blank" rel="noopener">Stock Unlock</a> infra · built as part of my off-boarding</span></summary>',
'',
'Built on the way out of full-time at [Stock Unlock](https://stockunlock.com) so the small, lean team can ship code changes and answer their own questions without needing me in chat day-to-day.',
'',
'- **Harness:** Private Discord bot (Discord.py) on EC2 + Docker Compose, calling an OpenHands harness with source-level patches.',
'- **`/code` is end-to-end full-stack engineering on demand.** Takes a plain-English ask in Discord, plans the change, writes the code (frontend, backend, or infra), opens a GitLab MR, and attaches Playwright screenshots (via the OpenHands browser tool) of the change actually running so a reviewer sees visual proof alongside the diff. Human-in-the-loop enforced via agent instructions, with code-side skip detection on the screenshot-approval step.',
'- **`/ask`** answers across a dozen read-only data sources: codebase, Aurora, PostHog, Stripe, RevenueCat, Sentry, and several more.',
'- **Reliability:** SQLite task tracking with orphan-conversation reconciliation on restart; thread-aware UX so multiple people can run jobs in parallel.',
'- **Models + cost:** two model tiers, Claude Sonnet 4.6 for `/code` and MiniMax M2.7 for `/ask`, selected via OpenHands and called through LiteLLM (API keys in AWS Secrets Manager).',
'- **Security boundary:** strict secret isolation, `/code` runs with deployer / Aurora-write / OpenSearch creds while `/ask` runs read-only-only. The `/code`-only secrets are explicitly deleted on each `/ask` invocation to prevent privilege escalation, even if a previous `/code` session left them in the workspace. IAM least-privilege between the agent and prod.',
'',
'<div class="md-stack">',
'  <div class="md-stack-row"><span class="md-stack-label">Backend</span><span class="md-stack-chips"><span>Python</span><span>Discord.py</span><span>OpenHands</span><span>Playwright</span><span>BrowserGym</span><span>GitLab API</span><span>LiteLLM</span></span></div>',
'  <div class="md-stack-row"><span class="md-stack-label">AWS</span><span class="md-stack-chips"><span>EC2</span><span>IAM</span><span>Secrets Manager</span><span>Aurora (Postgres)</span></span></div>',
'  <div class="md-stack-row"><span class="md-stack-label">Infra</span><span class="md-stack-chips"><span>Docker Compose</span><span>SQLite</span></span></div>',
'  <div class="md-stack-row"><span class="md-stack-label">External</span><span class="md-stack-chips"><span>PostHog</span><span>Stripe</span><span>RevenueCat</span></span></div>',
'</div>',
'',
'</details>',
'',
'<details class="work-collapse">',
'  <summary><strong>Customer.io to AWS SES migration</strong> <span class="muted"><a href="https://stockunlock.com" target="_blank" rel="noopener">Stock Unlock</a> · 27 days on the side</span></summary>',
'',
'Migrated transactional and marketing email off Customer.io across 27 days on the side. **Hundreds of thousands of emails per month, over a million a year, ~$5 to 6K per year saved.**',
'',
'- **Three send modes:** triggered (Lambda-direct), broadcasts (SQS-buffered + DLQs), campaigns (EventBridge-scheduled).',
'- **Self-serve composer for non-engineers:** three-button UI with live preview and locked design areas. Five minutes of training, anyone on the team can ship a broadcast.',
'- **Claude Code helper prompt:** a "Copy Agent Prompt" button copies a guided Q&A script into Claude. Claude walks the user through the email\'s purpose, audience, and structure, then hands back finished HTML they paste back into the composer. Non-technical users get a co-author, not a blank page.',
'- **Deliverability + tracking:** bounces, complaints, and unsubscribes auto-route to the suppression list via SES feedback loops. Full activity log of send/delivery/open/click counts, filterable by recipient, campaign, template, or status.',
'- **How I built it:** Claude Code wrote most of the code; I read the parts that mattered (security, deliverability, business logic) and shipped.',
'',
'<div class="md-stack">',
'  <div class="md-stack-row"><span class="md-stack-label">Backend</span><span class="md-stack-chips"><span>Python</span><span>FastAPI</span></span></div>',
'  <div class="md-stack-row"><span class="md-stack-label">AWS</span><span class="md-stack-chips"><span>SES</span><span>SNS</span><span>Lambda</span><span>Fargate</span><span>SQS</span><span>EventBridge</span><span>S3</span><span>Aurora (Postgres)</span></span></div>',
'  <div class="md-stack-row"><span class="md-stack-label">Frontend</span><span class="md-stack-chips"><span>TypeScript</span><span>React</span><span>MUI</span></span></div>',
'</div>',
'',
'</details>',
'',
'<details class="work-collapse">',
'  <summary><strong>Webflow to self-hosted marketing site</strong> <span class="muted"><a href="https://stockunlock.com" target="_blank" rel="noopener">Stock Unlock</a></span></summary>',
'',
'Migrated stockunlock.com off Webflow into a custom self-hosted codebase. Every line written by Claude Code, every commit reviewed by me. **~$500 to $1K per year saved** in hosting, contractor, and upkeep costs.',
'',
'- **20× more content pages.** Full UX control Webflow couldn\'t deliver.',
'- **Programmatic-SEO Lambdas** generate per-keyword and per-region pages, with GEO (Generative Engine Optimization) meta layered on for AI search. AI-generated, human-reviewed.',
'- **No more contractor dependency:** every copy update is a code change in our own repo.',
'',
'<div class="md-stack">',
'  <div class="md-stack-row"><span class="md-stack-label">Frontend</span><span class="md-stack-chips"><span>HTML</span><span>Tailwind CSS</span><span>JavaScript</span></span></div>',
'  <div class="md-stack-row"><span class="md-stack-label">Backend</span><span class="md-stack-chips"><span>Node.js</span><span>Handlebars</span></span></div>',
'  <div class="md-stack-row"><span class="md-stack-label">AWS</span><span class="md-stack-chips"><span>Lambda</span><span>CloudFront</span><span>S3</span></span></div>',
'</div>',
'',
'</details>',
'',
'<details class="work-collapse">',
'  <summary><strong>This site, jakeruth.com</strong> <span class="muted">Personal · AI-built, human-reviewed</span></summary>',
'',
'Vanilla HTML/CSS/JS, no build step, three chrome experiences sharing a single shell. Written by AI, reviewed by me.',
'',
'- **Three mediums (XP, README, SaaS)** deliver hard parity on every fact via shared canonical content.',
'- **Custom Rubik\'s-cube solver** computes the shortest move sequence between any two cube states; animates the transition between mediums.',
'- **`BACKBONE.md` + `CLAUDE.md`** live in the repo as canonical docs so any agent reading the codebase stays on-voice and parity stays enforced.',
'',
'<div class="md-stack">',
'  <div class="md-stack-row"><span class="md-stack-label">Frontend</span><span class="md-stack-chips"><span>HTML</span><span>CSS</span><span>Vanilla JS</span><span>Three.js</span></span></div>',
'  <div class="md-stack-row"><span class="md-stack-label">Hosting</span><span class="md-stack-chips"><span>GitHub Pages</span></span></div>',
'</div>',
'',
'</details>',
'',
'<details class="work-collapse">',
'  <summary><strong>Wirelessly-controlled blinds motor</strong> <span class="wip-pill">in progress</span> <span class="muted">Personal · first hardware project</span></summary>',
'',
'First hardware project I\'ve ever attempted. Building a battery-powered, Wi-Fi-controllable motor that pulls the bead chain on the roller shades in my apartment. Working bench-up from a Feather + breadboard toward a wall-mounted unit.',
'',
'- **What it is.** A small device that pulls a 4.5mm bead chain on a standard roller shade, eventually battery-powered and Wi-Fi-controllable. Currently bench-prototyping the Feather → DRV8833 → N20 motor chain over USB; battery + boost-converter pass and the FixMyBlinds clutch coupler come next.',
'- **Codex over Claude Code.** Tried both; for embedded work (voltage, motor torque, gear ratios, datasheet reading, board pinouts), Codex held the depth of conversation I needed for this project, so I switched. Long Codex sessions plan the next step; I go bench-test it.',
'- **The learning loop.** Early on I was effectively a robotic front-end for Codex, copying instructions and observing what happened. With iteration I\'m picking up the underlying systems, voltage, current, motor drivers, encoder feedback, LiPo + boost-converter behavior, and starting to ask better questions instead of just relaying.',
'- **Why it matters.** Pulling off a domain I\'ve never touched, in spare hours, is part of why I\'m convinced the 10x to 100x shift in engineer output is real and recent. Hardware was the toughest gap to bridge; with the right tooling, that gap is closing.',
'',
'<div class="md-stack">',
'  <div class="md-stack-row"><span class="md-stack-label">Firmware</span><span class="md-stack-chips"><span>C++ (Arduino)</span></span></div>',
'  <div class="md-stack-row"><span class="md-stack-label">Tooling</span><span class="md-stack-chips"><span>Codex</span><span>Arduino IDE</span></span></div>',
'  <div class="md-stack-row"><span class="md-stack-label">Microcontroller</span><span class="md-stack-chips"><span>Adafruit Feather ESP32-C6</span><span>Seeed XIAO ESP32-C6</span></span></div>',
'  <div class="md-stack-row"><span class="md-stack-label">Motor + driver</span><span class="md-stack-chips"><span>N20 DC motor (6V, 1:100, magnetic encoder)</span><span>DRV8833</span></span></div>',
'  <div class="md-stack-row"><span class="md-stack-label">Power</span><span class="md-stack-chips"><span>LiPo 3.7V 1200mAh</span><span>MiniBoost 5V (TPS61023)</span></span></div>',
'  <div class="md-stack-row"><span class="md-stack-label">Mechanical</span><span class="md-stack-chips"><span>FixMyBlinds Rollease R8 clutch</span><span>4.5mm bead chain</span></span></div>',
'</div>',
'',
'</details>',
'',
'## Mastery / hobbies',
'',
'Committing hard to things with depth has been the pattern through my life. Software engineering is the one that stuck. *"Self-improvement as a core operating system part of me."*',
'',
'<ul class="hobby-list-md">',
'  <li class="hobby-card-md">',
'    <div class="hobby-head"><strong>Speed-cubing</strong><span class="muted">2008–2014 · WCA (World Cube Association)</span></div>',
'    <div class="hobby-body">3×3 average <strong>13.95s</strong>. Top-20 in the US at the Pyraminx at peak. Competed at Northeast US events and Nationals (<a href="https://www.worldcubeassociation.org/persons/2008RUTH01" target="_blank" rel="noopener">WCA profile: 2008RUTH01</a>).</div>',
'  </li>',
'  <li class="hobby-card-md">',
'    <div class="hobby-head"><strong>Unicycle</strong><span class="muted">~12–16 months, HS junior year</span></div>',
'    <div class="hobby-body">Mountain unicycle, one-footed, forward and backward, stair jumps, mountain-trail riding, bench jumps. Eventually combined with cubing on stage at Oscar Health\'s company talent show. Twice.</div>',
'  </li>',
'  <li class="hobby-card-md">',
'    <div class="hobby-head"><strong>Track and field</strong><span class="muted">HS · Captain &amp; MVP senior year</span></div>',
'    <div class="hobby-body">Jumper events (high jump, triple jump, long jump). Also 400m and the occasional 4×400. Most points scored on the team.</div>',
'  </li>',
'  <li class="hobby-card-md">',
'    <div class="hobby-head"><strong>Soccer</strong><span class="muted">All four years HS</span></div>',
'    <div class="hobby-body">Played all four years of high school. JV captain sophomore year. Started on the varsity team senior year.</div>',
'  </li>',
'  <li class="hobby-card-md">',
'    <div class="hobby-head"><strong>Rugby</strong><span class="muted">UAlbany · B-squad → A-squad</span></div>',
'    <div class="hobby-body">Came in as a sport newcomer; moved up after learning the game.</div>',
'  </li>',
'  <li class="hobby-card-md">',
'    <div class="hobby-head"><strong>Rock climbing</strong><span class="muted">Oscar Health era · ~2 yrs</span></div>',
'    <div class="hobby-body">Indoor, steady climbing with friends from the team. Problem-solving with your body, plus the social side. Would pick it up again in a heartbeat.</div>',
'  </li>',
'  <li class="hobby-card-md">',
'    <div class="hobby-head"><strong>Skateboarding, DDR, Guitar Hero, RuneScape</strong><span class="muted">Teen years</span></div>',
'    <div class="hobby-body">Insanely good at DDR and Guitar Hero, very good at skateboarding, deep on RuneScape. The lock-in pattern was already showing.</div>',
'  </li>',
'  <li class="hobby-card-md">',
'    <div class="hobby-head"><strong>Math</strong><span class="muted">Since third grade</span></div>',
'    <div class="hobby-body">Skipped onto the accelerated track in third grade and stayed ahead through senior year of high school, burning through every available math class except AP Calc.</div>',
'  </li>',
'  <li class="hobby-card-md">',
'    <div class="hobby-head"><strong>Meditation</strong><span class="muted">Adult practice</span></div>',
'    <div class="hobby-body">In and out of the practice but generally enjoy meditating. Also into books on the subconscious mind, plus territory that borders on spirituality, Buddhism, and quantum-philosophy.</div>',
'  </li>',
'</ul>',
'',
'**The inverse signal.** A high school classmate told me once that I was good at everything that didn\'t matter. He wasn\'t wrong. The flip side of hyperfixation is that without the feedback loop, I tune out (bad student in English and history, doodled in class). The list above is what I got weirdly good at and then moved past, which is what makes the one that stuck, software engineering, stand out.',
'',
'<p>Open the <strong>Cube</strong> tab for an interactive Rubik\'s cube where every face is the GitHub Octocat in a different brand color. Scramble it to mix the stickers; Solve animates the optimal sequence (bidirectional BFS) all the way back home.</p>',
'',
'---',
'',
'<p class="md-bottom-note" id="bottom-note"><em>Made it to the bottom?</em> A working principle of mine: most of what\'s worked for me looks lucky in retrospect. AP CS to dodge AP Calc. The Tekkapalooza resume drop. The Oscar interview question. Daniel replying out of exhaustion. YC reaching out via LinkedIn. The pattern is that luck only lands on people who keep running at it. Not sure if you\'re into that worldview, but I\'ll shoot my shot, this is something I believe in.</p>',
'',
'<p class="muted" style="text-align:center; font-size:12px;">',
'  README.md · 100% built with AI (Claude Code), reviewed by Jake · ',
'  <a href="#top">back to top</a>',
'</p>',
''
].join('\n');
